// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.ChromaticAberration = (function(superClass) {
  extend(ChromaticAberration, superClass);

  function ChromaticAberration() {
    return ChromaticAberration.__super__.constructor.apply(this, arguments);
  }

  ChromaticAberration.effectName = "Chromatic Aberration";

  ChromaticAberration.prototype.fragmentShader = "uniform float rShift; //input name: \"Red Shift\", type: \"number\", min: 0, max: 1, default: 0.5\nuniform float gShift; //input name: \"Green Shift\", type: \"number\", min: 0, max: 1, default: 0.5\nuniform float bShift; //input name: \"Blue Shift\", type: \"number\", min: 0, max: 1, default: 0.5\nuniform vec2 uSize;\nvarying vec2 vUv;\nuniform sampler2D uTex;\n\nvoid main (void)\n{\n    float r = texture2D(uTex, vUv + vec2((2.0 * rShift - 1.0) * 0.05, 0.0)).r;\n    float g = texture2D(uTex, vUv + vec2((2.0 * gShift - 1.0) * 0.05, 0.0)).g;\n    float b = texture2D(uTex, vUv + vec2((2.0 * bShift - 1.0) * 0.05, 0.0)).b;\n    float a = max(r, max(g, b));\n    gl_FragColor = vec4(r, g, b, a);\n}";

  return ChromaticAberration;

})(ShaderPassBase);
