// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.DotRollPass = (function(superClass) {
  extend(DotRollPass, superClass);

  DotRollPass.effectName = "Rolling Dot Screen";

  function DotRollPass() {
    DotRollPass.__super__.constructor.call(this);
    this.time = 0;
  }

  DotRollPass.prototype.update = function() {
    this.time += 1;
    return this.uniforms.time.value = this.time;
  };

  DotRollPass.prototype.fragmentShader = "uniform sampler2D uTex;\nuniform float rollSpeed;\nuniform float time;\nvarying vec2 vUv;\nuniform vec2 uSize;\n\nconst float circleSize = 17.0;\nvoid main() {\n  vec2 p = mod(gl_FragCoord.xy, vec2(circleSize));\n  p -= vec2(circleSize / 2.0);\n  float dist = sqrt(dot(p, p));\n  if (dist + 3.0 < circleSize / 2.1)\n    gl_FragColor = texture2D(uTex, vUv);\n  else\n    discard;\n}";

  return DotRollPass;

})(ShaderPassBase);
