// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.FeedbackPass = (function(superClass) {
  extend(FeedbackPass, superClass);

  FeedbackPass.effectName = "Feedback";

  FeedbackPass.prototype.inputs = [
    {
      name: "Opacity",
      type: "number",
      min: 0,
      max: 1,
      "default": 0.5
    }
  ];

  function FeedbackPass(height, width) {
    var canvas, parameters, quad;
    FeedbackPass.__super__.constructor.call(this);
    this.needsSwap = true;
    this.enabled = true;
    parameters = {
      minFilter: THREE.LinearFilter,
      magFilter: THREE.LinearFilter,
      format: THREE.RGBAFormat,
      stencilBuffer: false,
      depthBuffer: false
    };
    canvas = document.querySelector('#output');
    this.fboWrite = new THREE.WebGLRenderTarget(canvas.width, canvas.height, parameters);
    this.fboRead = new THREE.WebGLRenderTarget(canvas.width, canvas.height, parameters);
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene;
    this.feedbackMaterial = new THREE.MeshBasicMaterial({
      map: this.fboRead.texture
    });
    this.feedbackMaterial.depthTest = false;
    this.feedbackMaterial.transparent = true;
    quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), this.feedbackMaterial);
    this.scene.add(quad);
    this.drawMaterial = new THREE.MeshBasicMaterial();
    this.drawMaterial.depthTest = false;
    this.drawMaterial.transparent = true;
    quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), this.drawMaterial);
    this.scene.add(quad);
  }

  FeedbackPass.prototype.swapBuffers = function() {
    var tmp;
    tmp = this.fboWrite;
    this.fboWrite = this.fboRead;
    return this.fboRead = tmp;
  };

  FeedbackPass.prototype.render = function(renderer, writeBuffer, readBuffer, delta) {
    this.feedbackMaterial.map = this.fboRead.texture;
    this.feedbackMaterial.opacity = this.get("Opacity");
    this.drawMaterial.map = (readBuffer != null ? readBuffer.texture : void 0) || readBuffer;
    renderer.setRenderTarget(writeBuffer);
    renderer.clear();
    renderer.render(this.scene, this.camera);
    renderer.setRenderTarget(this.fboWrite);
    renderer.clear();
    renderer.render(this.scene, this.camera);
    renderer.setRenderTarget(null);
    return this.swapBuffers();
  };

  return FeedbackPass;

})(EffectPassBase);
