// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.InvertPass = (function(superClass) {
  extend(InvertPass, superClass);

  function InvertPass() {
    return InvertPass.__super__.constructor.apply(this, arguments);
  }

  InvertPass.effectName = "Invert";

  InvertPass.prototype.fragmentShader = "uniform float amount; //input name: \"Invert Amount\", type: \"number\", min: 0, max: 1, default: 0\nuniform vec2 uSize;\nvarying vec2 vUv;\nuniform sampler2D uTex;\n\nvoid main (void)\n{\n    vec4 color = texture2D(uTex, vUv);\n    color = (1.0 - amount) * color + (amount) * (1.0 - color);\n    gl_FragColor = vec4(color.rgb, color.a);\n}";

  return InvertPass;

})(ShaderPassBase);
