// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.ISFEffect = (function(superClass) {
  extend(ISFEffect, superClass);

  function ISFEffect() {
    return ISFEffect.__super__.constructor.apply(this, arguments);
  }

  ISFEffect.fromFile = function(file, contents) {
    var NewEffect;
    return NewEffect = (function(superClass1) {
      extend(NewEffect, superClass1);

      function NewEffect() {
        return NewEffect.__super__.constructor.apply(this, arguments);
      }

      NewEffect.effectName = file.name;

      NewEffect.prototype.source = contents;

      return NewEffect;

    })(ISFEffect);
  };

  return ISFEffect;

})(EffectPassBase);
