// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.KaleidoscopePass = (function(superClass) {
  extend(KaleidoscopePass, superClass);

  function KaleidoscopePass() {
    return KaleidoscopePass.__super__.constructor.apply(this, arguments);
  }

  KaleidoscopePass.effectName = "Kaleidoscope";

  KaleidoscopePass.prototype.fragmentShader = "uniform float amount;\nuniform vec2 uSize;\nvarying vec2 vUv;\nuniform float size; //input name: \"Number of Sections\", type: \"number\", min:1, max:12, default:6, step:1\nuniform sampler2D uTex;\nuniform float time;\nuniform float fromCenter; //input name: \"From Center\", type: \"boolean\", toggle:true, default: true\n\nconst float NUM_SIDES = 6.0;\nconst float PI = 3.14159265359;\nconst float DEG_TO_RAD = PI / 180.0;\n\nvec2 Kaleidoscope( vec2 uv, float n, float bias ) {\n  float angle = PI / n;\n  \n  float r = length( uv );\n  float a = atan( uv.y, uv.x ) / angle;\n  \n  a = mix( fract( a ), 1.0 - fract( a ), mod( floor( a ), 2.0 ) ) * angle;\n  \n  return vec2( cos( a ), sin( a ) ) * r;\n}\n\n\nvoid main(void)\n{\n  vec2 uv = mix(vUv, vUv * 2.0 - 1.0, fromCenter);\n  uv = Kaleidoscope( uv * 2.0, size, time * 0.5 );\n  gl_FragColor =  texture2D(uTex,uv / 4.0 + 0.5);\n}";

  return KaleidoscopePass;

})(ShaderPassBase);
