// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.Passthrough = (function(superClass) {
  extend(Passthrough, superClass);

  function Passthrough() {
    return Passthrough.__super__.constructor.apply(this, arguments);
  }

  Passthrough.effectName = "Passthrough";

  Passthrough.prototype.fragmentShader = "uniform vec2 uSize;\nvarying vec2 vUv;\nuniform sampler2D uTex;\n\nvoid main (void)\n{\n    gl_FragColor = texture2D(uTex, vUv);\n}";

  return Passthrough;

})(ShaderPassBase);
