// Generated by CoffeeScript 1.12.7

/* 
Signals are used to generate values for driving inputs on effects and compositions

  inputs:
    name: User readable name
    type: boolean|number|select
    default: Value to initialize to
    options (only for select): Array of option values to show in the popup
    min (only for numbers): number
    max (only for numbers): number

  outputs:
    name: User readable name
    type: boolean|number|select|function
    default: Value to initialize to
    callback (only for function): String with name of member function to call back
      (observer, observingProperty) -> This function is called with the object that
      wants to observe this output.  See Midi.Midi Listen
    min (only for numbers): number
    max (only for numbers): number
 */
var VJSSignal,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSSignal = (function(superClass) {
  extend(VJSSignal, superClass);

  VJSSignal.prototype.inputs = [];

  VJSSignal.prototype.outputs = [];

  function VJSSignal() {
    VJSSignal.__super__.constructor.call(this);
    this.set("name", this.name);
  }

  VJSSignal.prototype.update = function(time) {};

  return VJSSignal;

})(VJSBindable);
