// Generated by CoffeeScript 1.12.7
var AudioVisualizer,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.AudioInput = (function(superClass) {
  extend(AudioInput, superClass);

  function AudioInput() {
    this.update = bind(this.update, this);
    this.startAudio = bind(this.startAudio, this);
    return AudioInput.__super__.constructor.apply(this, arguments);
  }

  AudioInput.prototype.readonly = true;

  AudioInput.MAX_AUDIO_LEVEL = 200;

  AudioInput.prototype.inputs = [
    {
      name: "gain",
      type: "number",
      min: 0,
      max: 1,
      "default": 0.1
    }
  ];

  AudioInput.prototype.outputs = [
    {
      name: "peak",
      type: "number",
      min: 0,
      max: 1
    }
  ];

  AudioInput.prototype.name = "Audio";

  AudioInput.prototype.customView = AudioVisualizer;

  AudioInput.prototype.outputProperty = 'peak';

  AudioInput.prototype.initialize = function() {
    navigator.getUserMedia_ = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
    navigator.getUserMedia_({
      audio: true
    }, this.startAudio, (function() {}));
    this.context = new AudioContext();
    this.analyzer = this.context.createAnalyser();
    return this.set("selectedFreq", 500);
  };

  AudioInput.prototype.startAudio = function(stream) {
    var mediaStreamSource;
    mediaStreamSource = this.context.createMediaStreamSource(stream);
    return mediaStreamSource.connect(this.analyzer);
  };

  AudioInput.prototype.update = function() {
    if (!this.data) {
      this.data = new Uint8Array(this.analyzer.frequencyBinCount);
      this.set("data", this.data);
    }
    this.analyzer.getByteFrequencyData(this.data);
    this.set("peak", this.data[this.get('selectedFreq')] / AudioInput.MAX_AUDIO_LEVEL * this.get('gain') / 0.1);
    return this.trigger("change:data");
  };

  AudioInput.prototype.getCustomViews = function() {
    return [
      new AudioVisualizer({
        model: this
      })
    ];
  };

  return AudioInput;

})(VJSSignal);

AudioVisualizer = (function(superClass) {
  extend(AudioVisualizer, superClass);

  function AudioVisualizer() {
    this.clickCanvas = bind(this.clickCanvas, this);
    this.mouseOut = bind(this.mouseOut, this);
    this.drag = bind(this.drag, this);
    this.render = bind(this.render, this);
    this.update = bind(this.update, this);
    return AudioVisualizer.__super__.constructor.apply(this, arguments);
  }

  AudioVisualizer.prototype.className = 'signal';

  AudioVisualizer.prototype.events = {
    "mousemove canvas": "drag",
    "mouseout canvas": "mouseOut",
    "click canvas": "clickCanvas"
  };

  AudioVisualizer.prototype.initialize = function() {
    this.canvas = document.createElement('canvas');
    this.el.appendChild(this.canvas);
    this.canvas.width = 300;
    this.canvas.height = 120;
    this.hoveredFreq = null;
    this.listenTo(this.model, "change:data", this.update);
    return $(window).resize(this.render);
  };

  AudioVisualizer.prototype.update = function() {
    var amp, ctx, data, i, j, len, selectedFreq;
    if (!this.visible) {
      return;
    }
    data = this.model.get('data');
    selectedFreq = this.model.get('selectedFreq');
    if (!data) {
      return;
    }
    this.scale = this.canvas.width / data.length;
    ctx = this.canvas.getContext('2d');
    ctx.save();
    ctx.fillStyle = "rgba(0,0,0,0.4)";
    ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    ctx.translate(0, this.canvas.height);
    ctx.scale(this.scale, this.scale);
    ctx.translate(0, -this.canvas.height);
    ctx.beginPath();
    ctx.strokeStyle = "#FF0000";
    ctx.moveTo(0, this.canvas.height);
    for (i = j = 0, len = data.length; j < len; i = ++j) {
      amp = data[i];
      ctx.lineTo(i, this.canvas.height - amp);
    }
    ctx.stroke();
    ctx.beginPath();
    ctx.strokeStyle = "#FF0000";
    ctx.moveTo(selectedFreq, this.canvas.height);
    ctx.lineTo(selectedFreq, 0);
    ctx.stroke();
    if (this.hoveredFreq) {
      ctx.beginPath();
      ctx.strokeStyle = "#FFFFFF";
      ctx.moveTo(this.hoveredFreq, 0);
      ctx.lineTo(this.hoveredFreq, this.canvas.height);
      ctx.stroke();
    }
    this.level = this.model.get('peak') * this.canvas.height;
    ctx.restore();
    ctx.fillStyle = "#FF0000";
    return ctx.fillRect(this.canvas.width - 10, this.canvas.height - this.level, 10, this.canvas.height);
  };

  AudioVisualizer.prototype.render = function() {
    this.canvas.width = this.canvas.parentNode.offsetWidth || 300;
    return this.el;
  };

  AudioVisualizer.prototype.drag = function(e) {
    return this.hoveredFreq = parseInt(e.offsetX / this.scale);
  };

  AudioVisualizer.prototype.mouseOut = function(e) {
    return this.hoveredFreq = null;
  };

  AudioVisualizer.prototype.clickCanvas = function(e) {
    return this.model.set("selectedFreq", parseInt(e.offsetX / this.scale));
  };

  return AudioVisualizer;

})(Backbone.View);
