// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.Clock = (function(superClass) {
  extend(Clock, superClass);

  function Clock() {
    this.clearTaps = bind(this.clearTaps, this);
    this["change:BPMTap"] = bind(this["change:BPMTap"], this);
    this["change:DownBeat"] = bind(this["change:DownBeat"], this);
    return Clock.__super__.constructor.apply(this, arguments);
  }

  Clock.prototype.name = "Clock";

  Clock.prototype.readonly = true;

  Clock.prototype.inputs = [
    {
      name: "BPM",
      type: "number",
      min: 1,
      max: 300,
      "default": 80
    }, {
      name: "BPMTap",
      type: "boolean"
    }, {
      name: "DownBeat",
      type: "boolean"
    }
  ];

  Clock.prototype.outputs = [
    {
      name: "Beat",
      type: "boolean"
    }, {
      name: "Downbeat",
      type: "boolean"
    }, {
      name: "BeatNumber",
      type: "number",
      min: 1,
      max: 8
    }, {
      name: "Smoothbeat",
      type: "number",
      min: 0,
      max: 1
    }, {
      name: "Measure",
      type: "number",
      min: 0,
      max: 1
    }
  ];

  Clock.prototype.initialize = function() {
    Clock.__super__.initialize.call(this);
    this.downTime = 0;
    this.taps = [];
    return application.globalSignals.Clock = this;
  };

  Clock.prototype["change:DownBeat"] = function(model, down) {
    if (down) {
      return this.downTime = Date.now();
    }
  };

  Clock.prototype["change:BPMTap"] = function(model, down) {
    var dt, i, j, next, periodMS, ref, t, tap, totalDelta;
    if (!down) {
      return;
    }
    t = Date.now();
    if (this.taps.length === 0) {
      this.downTime = t;
    }
    this.taps.push(t);
    if (this.taps.length > 4) {
      totalDelta = 0;
      for (i = j = 0, ref = this.taps.length - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        tap = this.taps[i];
        next = this.taps[i + 1];
        dt = next - tap;
        totalDelta += dt;
      }
      periodMS = totalDelta / (this.taps.length - 1);
      this.set("BPM", 60000 / periodMS);
    }
    if (this.clearTimer) {
      clearTimeout(this.clearTimer);
    }
    return this.clearTimer = setTimeout(this.clearTaps, 3000);
  };

  Clock.prototype.clearTaps = function() {
    return this.taps = [];
  };

  Clock.prototype.update = function(time) {
    var beatNumber, measuretime, percentInBeat, periodMS, timeInBeat, timeSinceDown;
    periodMS = 60 / this.get("BPM") * 1000;
    timeSinceDown = time - this.downTime;
    beatNumber = Math.floor(timeSinceDown / periodMS);
    measuretime = Math.fract(timeSinceDown / (periodMS * 4));
    this.set("Measure", measuretime);
    timeInBeat = timeSinceDown % periodMS;
    percentInBeat = timeInBeat / periodMS;
    if (percentInBeat < this.lastPercent) {
      this.set("Beat", true);
      if (beatNumber % 4 === 0) {
        this.set("Downbeat", true);
      }
      this.set("BeatNumber", (beatNumber % 8) + 1);
    } else {
      this.set("Beat", false);
      this.set("Downbeat", false);
    }
    this.lastPercent = percentInBeat;
    return this.set("Smoothbeat", percentInBeat);
  };

  return Clock;

})(VJSSignal);
