// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.ColorGenerator = (function(superClass) {
  extend(ColorGenerator, superClass);

  function ColorGenerator() {
    this.update = bind(this.update, this);
    this.change = bind(this.change, this);
    return ColorGenerator.__super__.constructor.apply(this, arguments);
  }

  ColorGenerator.prototype.inputs = [
    {
      name: "hue",
      type: "number",
      min: 0,
      max: 1
    }, {
      name: "saturation",
      type: "number",
      min: 0,
      max: 1
    }, {
      name: "brightness",
      type: "number",
      min: 0,
      max: 1
    }
  ];

  ColorGenerator.prototype.outputs = [
    {
      name: "color",
      type: "color"
    }
  ];

  ColorGenerator.prototype.outputProperty = "color";

  ColorGenerator.prototype.name = "Color";

  ColorGenerator.prototype.initialize = function() {
    ColorGenerator.__super__.initialize.call(this);
    return this.listenTo(this, "change", this.change);
  };

  ColorGenerator.prototype.change = function() {
    return this.set("color", Color.hsl(this.get('hue'), this.get('saturation'), this.get('brightness')));
  };

  ColorGenerator.prototype.update = function(time) {
    var period, value;
    time = time / 1000;
    period = this.get("period");
    value = 0;
    switch (this.get("type")) {
      case "Sin":
        value = Math.sin(Math.PI * time / period) * .5 + .5;
        break;
      case "Square":
        value = Math.round(Math.sin(Math.PI * time / period) * .5 + .5);
        break;
      case "Sawtooth Up":
        value = time / period;
        value = value - Math.floor(value);
        break;
      case "Sawtooth Down":
        value = time / period;
        value = 1 - (value - Math.floor(value));
    }
    return this.set("value", value);
  };

  return ColorGenerator;

})(VJSSignal);
