// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.FallingSignal = (function(superClass) {
  extend(FallingSignal, superClass);

  function FallingSignal() {
    this["change:in"] = bind(this["change:in"], this);
    return FallingSignal.__super__.constructor.apply(this, arguments);
  }

  FallingSignal.prototype.inputs = [
    {
      name: "in",
      type: "number",
      min: 0,
      max: 1,
      "default": 0
    }, {
      name: "fallSpeed",
      type: "number",
      min: 0,
      max: 1,
      "default": .3
    }
  ];

  FallingSignal.prototype.outputs = [
    {
      name: "out",
      type: "number",
      min: 0,
      max: 1,
      "default": 0
    }
  ];

  FallingSignal.prototype.name = "Fall";

  FallingSignal.prototype["change:in"] = function(obj, val) {};

  FallingSignal.prototype.update = function(time) {
    var input, out;
    input = this.get("in");
    out = this.get("out");
    if (input > out) {
      out = input;
    }
    out -= this.get("fallSpeed") * .1;
    out = Math.clamp(out, 0, 1);
    return this.set("out", out);
  };

  return FallingSignal;

})(VJSSignal);
