// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.Gamepad = (function(superClass) {
  extend(Gamepad, superClass);

  Gamepad.prototype.hidden = true;

  Gamepad.prototype.name = "Gamepad";

  Gamepad.prototype.outputs = [
    {
      name: "Gamepad Listen",
      type: "function",
      callback: "listenForNext",
      hidden: true
    }
  ];

  function Gamepad() {
    this.update = bind(this.update, this);
    this.listenForNext = bind(this.listenForNext, this);
    this.checkForPad = bind(this.checkForPad, this);
    Gamepad.__super__.constructor.call(this);
    requestAnimationFrame(this.checkForPad);
  }

  Gamepad.prototype.checkForPad = function() {
    if (navigator.getGamepads && navigator.getGamepads()[0]) {
      return this.pad = navigator.getGamepads()[0];
    } else {
      return requestAnimationFrame(this.checkForPad);
    }
  };

  Gamepad.prototype.listenForNext = function(observer, observingProperty) {
    this.listenNext = true;
    this.nextObserver = observer;
    return this.nextObservingProperty = observingProperty;
  };

  Gamepad.prototype.buttonEvent = function(key, value) {
    if (this.listenNext) {
      this.nextObserver.bindToKey(this.nextObservingProperty, this, key);
      this.listenNext = false;
      this.nextObserver = null;
      this.nextObservingProperty = null;
    }
    return this.set(key, value);
  };

  Gamepad.prototype.axisEvent = function(pad, axisIndex) {
    var key, lastValue, value;
    key = pad.index + "-Axis" + axisIndex;
    value = pad.axes[axisIndex];
    lastValue = this.lastAxes[axisIndex];
    if (this.listenNext && Math.abs(lastValue - value) > .1) {
      this.nextObserver.bindToKey(this.nextObservingProperty, this, key);
      this.listenNext = false;
      this.nextObserver = null;
      this.nextObservingProperty = null;
    }
    value = (value + 1) / 2;
    if (axisIndex === 1 || axisIndex === 3) {
      value = 1 - value;
    }
    return this.set(key, value);
  };

  Gamepad.prototype.update = function() {
    var axis, button, i, j, k, len, len1, pad, ref, ref1;
    pad = navigator.getGamepads()[0];
    if (pad && this.lastPad) {
      ref = Gamepad.BUTTONS;
      for (j = 0, len = ref.length; j < len; j++) {
        button = ref[j];
        if (pad.buttons[button] !== this.lastButtons[button]) {
          this.buttonEvent(pad.index + "-" + button, pad.buttons[button]);
        }
      }
      ref1 = pad.axes;
      for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
        axis = ref1[i];
        if (axis !== this.lastAxes[i]) {
          this.axisEvent(pad, i);
        }
      }
    }
    this.lastPad = pad;
    this.lastButtons = pad != null ? pad.buttons : void 0;
    return this.lastAxes = pad != null ? pad.axes : void 0;
  };

  Gamepad.FACE_1 = 0;

  Gamepad.FACE_2 = 1;

  Gamepad.FACE_3 = 2;

  Gamepad.FACE_4 = 3;

  Gamepad.LEFT_SHOULDER = 4;

  Gamepad.RIGHT_SHOULDER = 5;

  Gamepad.LEFT_SHOULDER_BOTTOM = 6;

  Gamepad.RIGHT_SHOULDER_BOTTOM = 7;

  Gamepad.SELECT = 8;

  Gamepad.START = 9;

  Gamepad.LEFT_ANALOGUE_STICK = 10;

  Gamepad.RIGHT_ANALOGUE_STICK = 11;

  Gamepad.PAD_TOP = 12;

  Gamepad.PAD_BOTTOM = 13;

  Gamepad.PAD_LEFT = 14;

  Gamepad.PAD_RIGHT = 15;

  Gamepad.STICK_1 = 16;

  Gamepad.STICK_2 = 17;

  Gamepad.BUTTONS = [Gamepad.FACE_1, Gamepad.FACE_2, Gamepad.FACE_3, Gamepad.FACE_4, Gamepad.LEFT_SHOULDER, Gamepad.RIGHT_SHOULDER, Gamepad.LEFT_SHOULDER_BOTTOM, Gamepad.RIGHT_SHOULDER_BOTTOM, Gamepad.SELECT, Gamepad.START, Gamepad.LEFT_ANALOGUE_STICK, Gamepad.RIGHT_ANALOGUE_STICK, Gamepad.PAD_TOP, Gamepad.PAD_BOTTOM, Gamepad.PAD_LEFT, Gamepad.PAD_RIGHT];

  return Gamepad;

})(VJSSignal);
