// Generated by CoffeeScript 1.12.7
var InvertSignal,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

InvertSignal = (function(superClass) {
  extend(InvertSignal, superClass);

  function InvertSignal() {
    return InvertSignal.__super__.constructor.apply(this, arguments);
  }

  InvertSignal.prototype.inputs = [
    {
      name: "input",
      type: "number",
      min: 0,
      max: 1,
      "default": 0
    }
  ];

  InvertSignal.prototype.outputs = [
    {
      name: "value",
      type: "number",
      min: 0,
      max: 1
    }
  ];

  InvertSignal.prototype.name = "Invert";

  InvertSignal.prototype.update = function(time) {
    return this.set("value", 1 - this.get("input"));
  };

  return InvertSignal;

})(VJSSignal);
