// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.Keyboard = (function(superClass) {
  extend(Keyboard, superClass);

  Keyboard.prototype.name = "Keyboard";

  Keyboard.prototype.hidden = true;

  Keyboard.prototype.inputs = [
    {
      name: "Listen",
      type: "boolean"
    }
  ];

  Keyboard.prototype.outputs = [
    {
      name: "Listen",
      type: "function",
      callback: "listenForNext",
      hidden: true
    }
  ];

  function Keyboard() {
    this.listenForNext = bind(this.listenForNext, this);
    this.up = bind(this.up, this);
    this.down = bind(this.down, this);
    Keyboard.__super__.constructor.call(this);
    $(document).keydown(this.down);
    $(document).keyup(this.up);
  }

  Keyboard.prototype.down = function(e) {
    var controlKey;
    controlKey = String.fromCharCode(e.keyCode);
    if (this.listenNext) {
      this.nextObserver.bindToKey(this.nextObservingProperty, this, controlKey);
      this.listenNext = false;
      this.nextObserver = null;
      this.nextObservingProperty = null;
    }
    return this.set(controlKey, true);
  };

  Keyboard.prototype.up = function(e) {
    var code;
    code = String.fromCharCode(e.keyCode);
    return this.set(code, false);
  };

  Keyboard.prototype.listenForNext = function(observer, observingProperty) {
    this.listenNext = true;
    this.nextObserver = observer;
    return this.nextObservingProperty = observingProperty;
  };

  return Keyboard;

})(VJSSignal);
