// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.LFO = (function(superClass) {
  extend(LFO, superClass);

  function LFO() {
    return LFO.__super__.constructor.apply(this, arguments);
  }

  LFO.prototype.inputs = [
    {
      name: "measuretime",
      type: "number",
      min: 0,
      max: 1,
      autoconnect: "Clock.Measure",
      hidden: true
    }, {
      name: "Clock Sync",
      type: "boolean",
      toggle: true
    }, {
      name: "period",
      type: "number",
      min: 0,
      max: 10,
      "default": 2
    }, {
      name: "type",
      type: "select",
      options: ["Sin", "Square", "Triangle", "Sawtooth Up", "Sawtooth Down"],
      "default": "Sin"
    }
  ];

  LFO.prototype.outputs = [
    {
      name: "value",
      type: "number",
      min: 0,
      max: 1
    }
  ];

  LFO.prototype.name = "LFO";

  LFO.prototype.update = function(time) {
    var period, value;
    value = 0;
    if (this.get("Clock Sync")) {
      time = this.get("measuretime");
      period = .5;
    } else {
      time = time / 1000;
      period = this.get("period");
    }
    switch (this.get("type")) {
      case "Sin":
        value = Math.sin(Math.PI * time / period) * .5 + .5;
        break;
      case "Square":
        value = Math.round(Math.sin(Math.PI * time / period) * .5 + .5);
        break;
      case "Sawtooth Up":
        value = time / period;
        value = value - Math.floor(value);
        break;
      case "Sawtooth Down":
        value = time / period;
        value = 1 - (value - Math.floor(value));
    }
    return this.set("value", value);
  };

  return LFO;

})(VJSSignal);
