// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.MIDI = (function(superClass) {
  extend(MIDI, superClass);

  MIDI.prototype.name = "MIDI";

  MIDI.prototype.hidden = true;

  MIDI.prototype.inputs = [
    {
      name: "Listen",
      type: "boolean"
    }
  ];

  MIDI.prototype.outputs = [
    {
      name: "MIDI Listen",
      type: "function",
      callback: "listenForNext",
      hidden: true
    }
  ];

  function MIDI() {
    this.errorHandler = bind(this.errorHandler, this);
    this.requestSuccess = bind(this.requestSuccess, this);
    this.onMIDIMessage = bind(this.onMIDIMessage, this);
    this.listenForNext = bind(this.listenForNext, this);
    MIDI.__super__.constructor.call(this);
    if (navigator.requestMIDIAccess) {
      navigator.requestMIDIAccess().then(this.requestSuccess, this.errorHandler);
    } else {
      console.error("Enable Midi access in chrome://flags");
    }
  }

  MIDI.prototype.listenForNext = function(observer, observingProperty) {
    if (!this.midi) {
      alert("You need to enable midi in chrome://flags to use this");
      return;
    }
    this.listenNext = true;
    this.nextObserver = observer;
    return this.nextObservingProperty = observingProperty;
  };

  MIDI.prototype.onMIDIMessage = function(message) {
    var controlKey;
    controlKey = message.data[0] + ":" + message.data[1];
    if (this.listenNext) {
      this.nextObserver.bindToKey(this.nextObservingProperty, this, controlKey);
      this.listenNext = false;
      this.nextObserver = null;
      this.nextObservingProperty = null;
    }
    return this.set(controlKey, message.data[2] / 127);
  };

  MIDI.prototype.requestSuccess = function(access) {
    var i, input, len, ref, results;
    this.midi = access;
    ref = this.midi.inputs.values();
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      input = ref[i];
      console.log(input, this.onMidiMessage);
      results.push(input.onmidimessage = this.onMIDIMessage);
    }
    return results;
  };

  MIDI.prototype.errorHandler = function(e) {
    return console.log(e);
  };

  return MIDI;

})(VJSSignal);
