// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.Palette = (function(superClass) {
  extend(Palette, superClass);

  function Palette() {
    return Palette.__super__.constructor.apply(this, arguments);
  }

  Palette.prototype.name = "Palette";

  Palette.prototype.inputs = [
    {
      name: "A",
      type: "color",
      "default": "#D6835B"
    }, {
      name: "B",
      type: "color",
      "default": "#AC627D"
    }, {
      name: "C",
      type: "color",
      "default": "#2D384C"
    }
  ];

  Palette.prototype.outputs = [
    {
      name: "A",
      type: "color",
      hidden: true
    }, {
      name: "B",
      type: "color",
      hidden: true
    }, {
      name: "C",
      type: "color",
      hidden: true
    }
  ];

  Palette.prototype.initialize = function() {
    return Palette.__super__.initialize.call(this);
  };

  return Palette;

})(VJSSignal);
