// Generated by CoffeeScript 1.12.7
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.Sequencer = (function(superClass) {
  extend(Sequencer, superClass);

  function Sequencer() {
    this.changeBeatNumber = bind(this.changeBeatNumber, this);
    this.clearPulse = bind(this.clearPulse, this);
    this.pulse = bind(this.pulse, this);
    return Sequencer.__super__.constructor.apply(this, arguments);
  }

  Sequencer.prototype.name = "Sequencer";

  Sequencer.prototype.inputs = [
    {
      name: "beat1",
      type: "boolean",
      toggle: true
    }, {
      name: "beat2",
      type: "boolean",
      toggle: true
    }, {
      name: "beat3",
      type: "boolean",
      toggle: true
    }, {
      name: "beat4",
      type: "boolean",
      toggle: true
    }, {
      name: "beat5",
      type: "boolean",
      toggle: true
    }, {
      name: "beat6",
      type: "boolean",
      toggle: true
    }, {
      name: "beat7",
      type: "boolean",
      toggle: true
    }, {
      name: "beat8",
      type: "boolean",
      toggle: true
    }, {
      name: "beatNumber",
      type: "number"
    }
  ];

  Sequencer.prototype.outputs = [
    {
      name: "pulse",
      type: "boolean"
    }, {
      name: "steady",
      type: "boolean"
    }
  ];

  Sequencer.prototype.initialize = function() {
    Sequencer.__super__.initialize.call(this);
    this.clock = application.clock;
    this.bindToKey({
      name: "beatNumber"
    }, this.clock, "BeatNumber");
    return this.listenTo(this, "change:beatNumber", this.changeBeatNumber);
  };

  Sequencer.prototype.pulse = function() {
    this.set("pulse", true);
    return requestAnimationFrame(this.clearPulse);
  };

  Sequencer.prototype.clearPulse = function() {
    return this.set("pulse", false);
  };

  Sequencer.prototype.changeBeatNumber = function(seq, beat) {
    if (this.get("beat" + beat)) {
      this.set("steady", true);
      return this.pulse();
    } else {
      return this.set("steady", false);
    }
  };

  Sequencer.prototype.update = function(time) {
    var lastBeat, period, value;
    lastBeat = this.beat;
    this.beat = time = time / 1000;
    period = this.get("period");
    value = 0;
    switch (this.get("type")) {
      case "Sin":
        value = Math.sin(Math.PI * time / period) * .5 + .5;
        break;
      case "Square":
        value = Math.round(Math.sin(Math.PI * time / period) * .5 + .5);
        break;
      case "Sawtooth Up":
        value = time / period;
        value = value - Math.floor(value);
        break;
      case "Sawtooth Down":
        value = time / period;
        value = 1 - (value - Math.floor(value));
    }
    return this.set("value", value);
  };

  return Sequencer;

})(VJSSignal);
