// Generated by CoffeeScript 1.12.7
var InkPass,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

InkPass = (function(superClass) {
  extend(InkPass, superClass);

  function InkPass() {
    return InkPass.__super__.constructor.apply(this, arguments);
  }

  InkPass.effectName = "Ink";

  InkPass.prototype.fragmentShader = "uniform sampler2D uTex;\nuniform float strength; //input name: \"Strength\", type: \"number\", min: 0, max: 10, default: 0.2\nuniform vec2 uSize;\nvarying vec2 vUv;\nvoid main() {\n    vec2 dx = vec2(1.0 / uSize.x, 0.0);\n    vec2 dy = vec2(0.0, 1.0 / uSize.y);\n    vec4 color = texture2D(uTex, vUv);\n    float bigTotal = 0.0;\n    float smallTotal = 0.0;\n    vec3 bigAverage = vec3(0.0);\n    vec3 smallAverage = vec3(0.0);\n    for (float x = -2.0; x <= 2.0; x += 1.0) {\n        for (float y = -2.0; y <= 2.0; y += 1.0) {\n            vec3 sample = texture2D(uTex, vUv + dx * x + dy * y).rgb;\n            bigAverage += sample;\n            bigTotal += 1.0;\n            if (abs(x) + abs(y) < 2.0) {\n                smallAverage += sample;\n                smallTotal += 1.0;\n            }\n        }\n    }\n    vec3 edge = max(vec3(0.0), bigAverage / bigTotal - smallAverage / smallTotal);\n    gl_FragColor = vec4(color.rgb - dot(edge, edge) * strength * 100000.0, color.a);\n}";

  return InkPass;

})(ShaderPassBase);
