// Generated by CoffeeScript 1.12.7
var NoisePass,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

NoisePass = (function(superClass) {
  extend(NoisePass, superClass);

  function NoisePass() {
    return NoisePass.__super__.constructor.apply(this, arguments);
  }

  NoisePass.effectName = "Add Noise";

  NoisePass.prototype.fragmentShader = "uniform sampler2D uTex;\nuniform float time;\nuniform float amount; //input name: \"Amount\", type: \"number\", min: 0, max: 1\nvarying vec2 vUv;\nfloat rand(vec2 co) {\n  return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);\n}\nvoid main() {\n  vec4 color = texture2D(uTex, vUv);\n  \n  float diff = (rand(vUv + time) - 0.5) * amount;\n  color.r += diff;\n  color.g += diff;\n  color.b += diff;\n  \n  gl_FragColor = color;\n}";

  return NoisePass;

})(ShaderPassBase);
