// Generated by CoffeeScript 1.12.7
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

this.ZoomBlurPass = (function(superClass) {
  extend(ZoomBlurPass, superClass);

  function ZoomBlurPass() {
    return ZoomBlurPass.__super__.constructor.apply(this, arguments);
  }

  ZoomBlurPass.effectName = "Zoom Blur";

  ZoomBlurPass.prototype.fragmentShader = "uniform sampler2D uTex;\nuniform vec2 centerIn;\nuniform float strength; //input name: \"Strength\", type: \"number\", max: 1, min: 0, default: 0\nuniform vec2 uSize;\nvarying vec2 vUv;\n\nfloat random(vec3 scale, float seed) {\n  /* use the fragment position for a different seed per-pixel */\n  return fract(sin(dot(gl_FragCoord.xyz + seed, scale)) * 43758.5453 + seed);\n}\n\nvoid main() {\n    vec4 baseColor = texture2D(uTex, vUv);\n    vec4 blurredColor = vec4(0.0);\n    float total = 0.0;\n    vec2 center = uSize * vec2(0.5);\n    vec2 toCenter = center - vUv * uSize;\n    \n    /* randomize the lookup values to hide the fixed number of samples */\n    float offset = random(vec3(12.9898, 78.233, 151.7182), 0.0);\n    \n    for (float t = 0.0; t <= 40.0; t++) {\n        float percent = (t + offset) / 40.0;\n        float weight = 4.0 * (percent - percent * percent);\n        vec4 sampleColor = texture2D(uTex, vUv + toCenter * percent * strength / uSize);\n        blurredColor += sampleColor * weight;\n        total += weight;\n    }\n    \n    blurredColor = blurredColor / total;\n    gl_FragColor = mix(baseColor, blurredColor, strength);\n    gl_FragColor.a = 1.0;\n}";

  return ZoomBlurPass;

})(ShaderPassBase);
