// Generated by CoffeeScript 1.12.7
var VJSCell, VJSControl,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSControl = (function(superClass) {
  extend(VJSControl, superClass);

  function VJSControl(model, property) {
    this.property = property;
    this.showBindings = bind(this.showBindings, this);
    VJSControl.__super__.constructor.call(this, {
      model: model
    });
  }

  VJSControl.prototype.initialize = function() {
    this.$el.on("contextmenu", this.showBindings);
    return this.listenTo(this.model, "change:" + this.property.name, this.render);
  };

  VJSControl.prototype.showBindings = function(e) {
    var el;
    e.preventDefault();
    el = window.application.valueBinder.render();
    return window.application.valueBinder.show(e.pageX, e.pageY, this.model, this.property);
  };

  VJSControl.prototype.div = function(className, text) {
    var el;
    el = document.createElement('div');
    if (className) {
      el.className = className;
    }
    if (text) {
      el.textContent = text;
    }
    return el;
  };

  return VJSControl;

})(Backbone.View);

VJSCell = (function(superClass) {
  extend(VJSCell, superClass);

  function VJSCell() {
    this.close = bind(this.close, this);
    this.open = bind(this.open, this);
    this.toggleOpen = bind(this.toggleOpen, this);
    return VJSCell.__super__.constructor.apply(this, arguments);
  }

  VJSCell.prototype.className = "vjs-panel-cell";

  VJSCell.prototype.initialize = function() {
    var arrow;
    VJSCell.__super__.initialize.call(this);
    this.el.appendChild(arrow = _V.div('arrow'));
    return arrow.addEventListener('click', this.toggleOpen);
  };

  VJSCell.prototype.toggleOpen = function() {
    if (this.el.classList.contains('hidden')) {
      return this.open();
    } else {
      return this.close();
    }
  };

  VJSCell.prototype.open = function() {
    var i, len, ref, v;
    if (this.customViews) {
      ref = this.customViews;
      for (i = 0, len = ref.length; i < len; i++) {
        v = ref[i];
        v.visible = true;
      }
    }
    return this.el.classList.remove('hidden');
  };

  VJSCell.prototype.close = function() {
    var i, len, ref, v;
    if (this.customViews) {
      ref = this.customViews;
      for (i = 0, len = ref.length; i < len; i++) {
        v = ref[i];
        v.visible = false;
      }
    }
    return this.el.classList.add('hidden');
  };

  return VJSCell;

})(Backbone.View);
