// Generated by CoffeeScript 1.12.7
var CompositionPicker, CompositionSlot,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CompositionPicker = (function(superClass) {
  extend(CompositionPicker, superClass);

  CompositionPicker.prototype.className = "composition-picker";

  CompositionPicker.prototype.events = {
    "dragover": "dragover",
    "dragleave": "dragleave",
    "drop": "drop",
    "click .slot": "launch"
  };

  function CompositionPicker(layer) {
    this.layer = layer;
    this.render = bind(this.render, this);
    this.launch = bind(this.launch, this);
    this.drop = bind(this.drop, this);
    this.dragleave = bind(this.dragleave, this);
    this.dragover = bind(this.dragover, this);
    CompositionPicker.__super__.constructor.call(this);
    this.compositions = [];
  }

  CompositionPicker.prototype.dragover = function(e) {
    e.preventDefault();
    return this.el.classList.add('dragover');
  };

  CompositionPicker.prototype.dragleave = function(e) {
    e.preventDefault();
    return this.el.classList.remove('dragover');
  };

  CompositionPicker.prototype.drop = function(e) {
    var file;
    e.preventDefault();
    this.el.classList.remove('dragover');
    file = e.originalEvent.dataTransfer.files[0];
    return this.addCompositionFromFile(file);
  };

  CompositionPicker.prototype.addCompositionFromFile = function(file) {
    var composition;
    composition = null;
    if (file.type.indexOf("video") === 0) {
      composition = new VideoComposition(file);
    } else if (file.type.indexOf("image") === 0) {
      composition = new ImageComposition(file);
    } else if (file.name.indexOf(".isf") !== -1) {
      composition = new ISFComposition(file);
    }
    if (composition) {
      return this.addComposition(composition);
    } else {
      return alert("I don't know what to do with this file :(");
    }
  };

  CompositionPicker.prototype.addComposition = function(comp) {
    var slot;
    slot = new CompositionSlot({
      model: comp
    });
    this.compositions.push(comp);
    if (!comp.thumbnail) {
      comp.thumbnail = document.createElement('div');
      comp.thumbnail.className = 'composition-thumbnail-label';
      comp.thumbnail.textContent = comp.name || "Composition";
    }
    this.el.appendChild(slot.render());
    if (!comp._thumbnailGenerated && typeof comp.generateThumbnail === "function") {
      comp._thumbnailGenerated = true;
      setTimeout((function(_this) {
        return function() {
          try {
            return comp.generateThumbnail();
          } catch (error) {
            return console.error("Failed to generate composition thumbnail", error);
          }
        };
      })(this), 0);
    }
    return slot;
  };

  CompositionPicker.prototype.launch = function(e) {
    var cid, composition;
    cid = e.currentTarget.getAttribute("data-composition-id");
    composition = _.find(this.compositions, (function(comp) {
      return comp.cid === cid;
    }));
    return this.layer.setComposition(composition);
  };

  CompositionPicker.prototype.render = function() {
    return this.el;
  };

  return CompositionPicker;

})(Backbone.View);

CompositionSlot = (function(superClass) {
  extend(CompositionSlot, superClass);

  function CompositionSlot() {
    this.render = bind(this.render, this);
    this.activeChanged = bind(this.activeChanged, this);
    this.initialize = bind(this.initialize, this);
    return CompositionSlot.__super__.constructor.apply(this, arguments);
  }

  CompositionSlot.prototype.className = 'slot';

  CompositionSlot.prototype.initialize = function() {
    CompositionSlot.__super__.initialize.call(this);
    this.el.setAttribute("data-composition-id", this.model.cid);
    this.listenTo(this.model, "thumbnail-available", this.render);
    return this.listenTo(this.model, "change:active", this.activeChanged);
  };

  CompositionSlot.prototype.activeChanged = function(obj, val) {
    if (val) {
      return this.el.classList.add("active");
    } else {
      return this.el.classList.remove("active");
    }
  };

  CompositionSlot.prototype.render = function() {
    this.el.replaceChildren();
    if (this.model.thumbnail && this.model.thumbnail.nodeType) {
      this.el.appendChild(this.model.thumbnail);
    } else if (this.model.thumbnail) {
      this.el.textContent = this.model.thumbnail;
    } else {
      this.el.textContent = this.model.name || "Composition";
    }
    return this.el;
  };

  return CompositionSlot;

})(Backbone.View);
