// Generated by CoffeeScript 1.12.7
var CompositionInspector,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CompositionInspector = (function(superClass) {
  extend(CompositionInspector, superClass);

  function CompositionInspector() {
    return CompositionInspector.__super__.constructor.apply(this, arguments);
  }

  CompositionInspector.prototype.initialize = function() {
    this.stack = document.createElement("div");
    this.stack.className = "stack";
    return this.el.appendChild(this.stack);
  };

  CompositionInspector.prototype.setComposition = function(composition) {
    var ref;
    if ((ref = this.view) != null) {
      ref.remove();
    }
    if (composition) {
      this.view = new SignalUIBase({
        model: composition
      });
      this.view.open();
      return this.stack.appendChild(this.view.render());
    }
  };

  return CompositionInspector;

})(Backbone.View);
