// Generated by CoffeeScript 1.12.7
var EffectsManager, EffectsPanel,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

EffectsManager = (function(superClass) {
  extend(EffectsManager, superClass);

  function EffectsManager(composer) {
    this.composer = composer;
    this.moveEffect = bind(this.moveEffect, this);
    this.destroyEffect = bind(this.destroyEffect, this);
    EffectsManager.__super__.constructor.call(this);
    this.effectClasses = VJSLibrary.instance.get("effects");
    this.stack = [];
  }

  EffectsManager.prototype.addEffectToStack = function(effect) {
    this.stack.push(effect);
    this.listenTo(effect, "destroy", this.destroyEffect);
    this.composer.insertPass(effect, this.composer.passes.length - 1);
    return this.trigger("add-effect", effect);
  };

  EffectsManager.prototype.destroyEffect = function(effect) {
    this.stopListening(effect);
    return this.composer.removePass(effect);
  };

  EffectsManager.prototype.moveEffect = function(cid, newIndex) {
    var effect;
    effect = _.find(this.stack, function(el) {
      return el.cid === cid;
    });
    return this.composer.movePass(effect, newIndex + 1);
  };

  EffectsManager.prototype.serialize = function() {
    var effect, effects, i, len, ref;
    effects = [];
    ref = this.stack;
    for (i = 0, len = ref.length; i < len; i++) {
      effect = ref[i];
      effects.push(effect.serialize());
    }
    return effects;
  };

  return EffectsManager;

})(Backbone.Model);

EffectsPanel = (function(superClass) {
  extend(EffectsPanel, superClass);

  function EffectsPanel() {
    this.render = bind(this.render, this);
    this.destroyEffect = bind(this.destroyEffect, this);
    this.addEffect = bind(this.addEffect, this);
    this.insertEffectPanel = bind(this.insertEffectPanel, this);
    this.showPopup = bind(this.showPopup, this);
    this.sortupdate = bind(this.sortupdate, this);
    return EffectsPanel.__super__.constructor.apply(this, arguments);
  }

  EffectsPanel.prototype.className = "effects";

  EffectsPanel.prototype.events = {
    "click .add-button": "showPopup"
  };

  EffectsPanel.prototype.initialize = function() {
    this.panels = [];
    this.popup = new VJSPopup;
    this.addButton = document.createElement('div');
    this.addButton.className = 'add-effect add-button';
    this.stack = document.createElement('div');
    this.el.appendChild(this.stack);
    this.el.appendChild(this.addButton);
    this.listenTo(this.model, "change", this.render);
    this.listenTo(this.model, "add-effect", this.insertEffectPanel);
    this.render();
    $(this.stack).sortable({
      handle: '.label',
      axis: 'y'
    });
    return $(this.stack).on("sortupdate", this.sortupdate);
  };

  EffectsPanel.prototype.sortupdate = function(e, jui) {
    var modelid;
    modelid = jui.item[0].getAttribute("model-id");
    return this.model.moveEffect(modelid, jui.item.index());
  };

  EffectsPanel.prototype.showPopup = function(e) {
    var effect, i, len, ref, values;
    values = [];
    ref = this.model.effectClasses;
    for (i = 0, len = ref.length; i < len; i++) {
      effect = ref[i];
      values.push(effect.effectName || effect.name);
    }
    return this.popup.show({
      element: e.target
    }, values, this.addEffect);
  };

  EffectsPanel.prototype.insertEffectPanel = function(effect) {
    var effectPanel, v;
    this.panels.push(effectPanel = new SignalUIBase({
      model: effect
    }));
    effectPanel.open();
    this.listenTo(effect, "destroy", this.destroyEffect);
    v = effectPanel.render();
    return this.stack.appendChild(v);
  };

  EffectsPanel.prototype.addEffect = function(name) {
    var clazz;
    clazz = _.find(this.model.effectClasses, (function(s) {
      return s.effectName === name;
    }));
    return this.model.addEffectToStack(new clazz);
  };

  EffectsPanel.prototype.destroyEffect = function(effect) {
    var i, len, panel, ref, results;
    ref = this.panels;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      panel = ref[i];
      if (panel.model === effect) {
        results.push(panel.remove());
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  EffectsPanel.prototype.render = function() {
    this.addButton.textContent = "+ Add Effect";
    return this.el;
  };

  return EffectsPanel;

})(Backbone.View);
