// Generated by CoffeeScript 1.12.7
var LayerInspector,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

LayerInspector = (function(superClass) {
  extend(LayerInspector, superClass);

  function LayerInspector() {
    return LayerInspector.__super__.constructor.apply(this, arguments);
  }

  LayerInspector.prototype.initialize = function() {
    this.stack = document.createElement("div");
    this.stack.className = "stack";
    this.el.appendChild(this.stack);
    return this.stack.appendChild(new SignalUIBase({
      model: this.model
    }).render());
  };

  return LayerInspector;

})(Backbone.View);
