// Generated by CoffeeScript 1.12.7
var SignalUIBase,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SignalUIBase = (function(superClass) {
  extend(SignalUIBase, superClass);

  function SignalUIBase() {
    this.destroy = bind(this.destroy, this);
    return SignalUIBase.__super__.constructor.apply(this, arguments);
  }

  SignalUIBase.prototype.className = "signal-set hidden";

  SignalUIBase.prototype.events = {
    "click .close-button": "destroy"
  };

  SignalUIBase.prototype.initialize = function() {
    var close, label, ref;
    SignalUIBase.__super__.initialize.call(this);
    this.el.setAttribute('model-id', this.model.cid);
    this.inputViews = [];
    this.customViews = [];
    this.outputViews = [];
    if (!this.model.readonly) {
      this.el.appendChild(close = _V.div('close-button'));
    }
    this.el.appendChild(label = _V.div('label'));
    label.textContent = this.model.name;
    this.insertInputViews();
    this.insertCustomViews();
    if (((ref = this.model.outputs) != null ? ref.length : void 0) > 0) {
      this.inputStack.appendChild(document.createElement('hr'));
      return this.insertOutputViews();
    }
  };

  SignalUIBase.prototype.insertInputViews = function() {
    var el, i, input, len, ref, results, v;
    this.el.appendChild(this.inputStack = _V.div('input stack'));
    ref = this.model.inputs;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      input = ref[i];
      if (input.hidden) {
        continue;
      }
      this.inputStack.appendChild(el = _V.div('signal'));
      el.setAttribute("data-ui-type", input.type);
      el.textContent = input.name;
      v = this.newControl(input);
      el.appendChild(v.render());
      results.push(this.inputViews.push(v));
    }
    return results;
  };

  SignalUIBase.prototype.insertCustomViews = function() {
    var base, customViews, i, len, results, view;
    customViews = typeof (base = this.model).getCustomViews === "function" ? base.getCustomViews() : void 0;
    if (!!customViews) {
      results = [];
      for (i = 0, len = customViews.length; i < len; i++) {
        view = customViews[i];
        this.customViews.push(view);
        results.push(this.inputStack.appendChild(view.render()));
      }
      return results;
    }
  };

  SignalUIBase.prototype.insertOutputViews = function() {
    var el, i, len, output, ref, results, v;
    this.el.appendChild(this.outputStack = _V.div('output stack'));
    ref = this.model.outputs;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      output = ref[i];
      if (output.hidden) {
        continue;
      }
      this.outputStack.appendChild(el = _V.div('signal'));
      el.textContent = output.name;
      el.setAttribute("data-ui-type", output.type);
      v = this.newControl(output);
      this.outputViews.push(v);
      results.push(el.appendChild(v.render()));
    }
    return results;
  };

  SignalUIBase.prototype.render = function() {
    return this.el;
  };

  SignalUIBase.prototype.destroy = function() {
    return this.model.trigger('destroy', this.model);
  };

  SignalUIBase.prototype.newControl = function(input) {
    if (input.type === "number") {
      return new VJSSlider(this.model, input);
    } else if (input.type === "select") {
      return new VJSSelect(this.model, input);
    } else if (input.type === "boolean") {
      return new VJSButton(this.model, input);
    } else if (input.type === "color") {
      return new VJSColorPicker(this.model, input);
    } else if (input.type === "function") {
      return new VJSButton(this.model, input);
    }
  };

  return SignalUIBase;

})(VJSCell);
