// Generated by CoffeeScript 1.12.7
var SignalManager, SignalManagerView,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

SignalManager = (function(superClass) {
  extend(SignalManager, superClass);

  SignalManager.prototype.signalList = {
    name: "Signals",
    type: "select",
    options: ["Add Signal"],
    "default": "Add Signal"
  };

  function SignalManager() {
    SignalManager.__super__.constructor.call(this, [], {
      model: VJSSignal
    });
    this.set("Signals", "Add Signal");
    this.signalClasses = [];
    this.registerSignal(FallingSignal);
    this.registerSignal(LFO);
    this.registerSignal(Clock);
    this.registerSignal(Palette);
    this.registerSignal(ColorGenerator);
    this.registerSignal(Sequencer);
    this.on("destroy", this.remove);
  }

  SignalManager.prototype.registerSignal = function(signalClass) {
    this.signalClasses.push(signalClass);
    this.signalList.options.push(signalClass.name);
    return this.trigger('change:registration');
  };

  SignalManager.prototype.update = function(time) {
    var i, len, ref, results, signal;
    ref = this.models;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      signal = ref[i];
      results.push(signal.update(time));
    }
    return results;
  };

  SignalManager.prototype.serialize = function() {
    var data;
    data = {
      signals: []
    };
    this.each(function(signal) {
      var serial;
      serial = signal.serialize();
      if (serial.name) {
        return data.signals.push(serial);
      }
    });
    return data;
  };

  SignalManager.prototype.unserialize = function(state) {
    var i, len, ref, signal, signalInfo;
    ref = state.signals;
    for (i = 0, len = ref.length; i < len; i++) {
      signalInfo = ref[i];
      signal = VJSBindable.inflate(signalInfo);
      this.add(signal);
    }
    return state.signals;
  };

  return SignalManager;

})(Backbone.Collection);

SignalManagerView = (function(superClass) {
  extend(SignalManagerView, superClass);

  function SignalManagerView() {
    this.removeSignalView = bind(this.removeSignalView, this);
    this.createSignalView = bind(this.createSignalView, this);
    this.render = bind(this.render, this);
    this.addSignal = bind(this.addSignal, this);
    this.showPopup = bind(this.showPopup, this);
    this.addSignal = bind(this.addSignal, this);
    return SignalManagerView.__super__.constructor.apply(this, arguments);
  }

  SignalManagerView.prototype.events = {
    "click .add-button": "showPopup"
  };

  SignalManagerView.prototype.initialize = function() {
    this.views = {};
    this.listenTo(this.model, "add", this.createSignalView);
    this.listenTo(this.model, "remove", this.removeSignalView);
    this.listenTo(this.model, "change:registration", this.render);
    this.addButton = document.createElement('div');
    this.addButton.className = 'add-signal add-button';
    this.stack = document.createElement('div');
    this.el.appendChild(this.stack);
    this.el.appendChild(this.addButton);
    this.popup = new VJSPopup;
    return this.render();
  };

  SignalManagerView.prototype.addSignal = function(e) {
    if (e.target.value !== -1) {
      this.model.add(new this.model.signalClasses[e.target.value]);
      return e.target.selectedIndex = 0;
    }
  };

  SignalManagerView.prototype.showPopup = function(e) {
    var i, len, ref, signal, values;
    values = [];
    ref = this.model.signalClasses;
    for (i = 0, len = ref.length; i < len; i++) {
      signal = ref[i];
      values.push(signal.name);
    }
    return this.popup.show({
      element: e.target
    }, values, this.addSignal);
  };

  SignalManagerView.prototype.addSignal = function(name) {
    var clazz;
    clazz = _.find(this.model.signalClasses, (function(s) {
      return s.name === name;
    }));
    return this.model.add(new clazz);
  };

  SignalManagerView.prototype.render = function() {
    this.addButton.textContent = "+ Add Signal";
    return this.el;
  };

  SignalManagerView.prototype.createSignalView = function(signal) {
    var view;
    if (signal.hidden) {
      return;
    }
    this.views[signal.cid] = view = new SignalUIBase({
      model: signal
    });
    return this.stack.appendChild(view.render());
  };

  SignalManagerView.prototype.removeSignalView = function(signal) {
    return this.views[signal.cid].remove();
  };

  return SignalManagerView;

})(Backbone.View);
