// Generated by CoffeeScript 1.12.7

/*
Pass views as an array of objects with a name property and a view property
 */
var TabSet,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

TabSet = (function(superClass) {
  extend(TabSet, superClass);

  TabSet.prototype.className = 'tab-set';

  TabSet.prototype.events = {
    "click .tab-label": "show"
  };

  function TabSet(parent, views) {
    var i, j, label, len, ref, viewDesc;
    this.views = views;
    this.show = bind(this.show, this);
    TabSet.__super__.constructor.call(this);
    parent.appendChild(this.el);
    this.labels = document.createElement('div');
    this.el.appendChild(this.labels);
    this.labels.className = 'labels';
    this.contents = document.createElement('div');
    this.el.appendChild(this.contents);
    this.contents.className = 'contents';
    ref = this.views;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      viewDesc = ref[i];
      this.labels.appendChild(label = document.createElement('div'));
      label.className = 'tab-label';
      label.textContent = viewDesc.name;
      label.view = viewDesc.view;
      viewDesc.label = label;
      this.contents.appendChild(viewDesc.view);
      if (i === 0) {
        label.classList.add('active');
      } else {
        viewDesc.view.style.display = 'none';
      }
    }
  }

  TabSet.prototype.show = function(e) {
    var j, len, ref, results, viewDesc;
    ref = this.views;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      viewDesc = ref[j];
      if (viewDesc.view === e.target.view) {
        viewDesc.label.classList.add('active');
        results.push(viewDesc.view.style.display = 'block');
      } else {
        viewDesc.label.classList.remove('active');
        results.push(viewDesc.view.style.display = 'none');
      }
    }
    return results;
  };

  TabSet.prototype.render = function() {
    return this.el;
  };

  return TabSet;

})(Backbone.View);
