// Generated by CoffeeScript 1.12.7
var ValueBinder,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ValueBinder = (function(superClass) {
  extend(ValueBinder, superClass);

  function ValueBinder() {
    this.keydown = bind(this.keydown, this);
    this.mousedown = bind(this.mousedown, this);
    this.hide = bind(this.hide, this);
    this.show = bind(this.show, this);
    this.clickRow = bind(this.clickRow, this);
    this.render = bind(this.render, this);
    return ValueBinder.__super__.constructor.apply(this, arguments);
  }

  ValueBinder.prototype.className = "value-binder-popup";

  ValueBinder.prototype.events = {
    "click .binding-row": "clickRow"
  };

  ValueBinder.prototype.initialize = function() {
    return document.body.appendChild(this.el);
  };

  ValueBinder.prototype.render = function() {
    var i, j, len, len1, output, outputRow, ref, ref1, row, signal;
    this.el.replaceChildren();
    row = document.createElement('div');
    row.className = 'binding-row';
    row.textContent = "Clear Binding";
    row.signal = null;
    row.property = null;
    this.el.appendChild(row);
    this.el.appendChild(document.createElement('hr'));
    ref = this.model.models;
    for (i = 0, len = ref.length; i < len; i++) {
      signal = ref[i];
      row = document.createElement('div');
      row.className = 'binding-label';
      row.textContent = signal.name;
      this.el.appendChild(row);
      ref1 = signal.outputs;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        output = ref1[j];
        this.el.appendChild(outputRow = document.createElement('div'));
        outputRow.className = 'binding-row';
        outputRow.textContent = output.name;
        outputRow.signal = signal;
        outputRow.property = output.name;
      }
    }
    return this.el;
  };

  ValueBinder.prototype.clickRow = function(e) {
    var observer, output, property, signal, target;
    target = e.target;
    signal = target.signal;
    property = target.property;
    observer = this.currentModel;
    if (signal) {
      output = _.find(signal.outputs, (function(o) {
        return o.name === property;
      }));
      if (output.type === "function") {
        signal[output.callback](observer, this.currentProperty);
      } else {
        observer.bindToKey(this.currentProperty, signal, property);
      }
    } else {
      observer.clearBinding(this.currentProperty.name);
    }
    return this.hide();
  };

  ValueBinder.prototype.show = function(x, y, model, property) {
    this.currentModel = model;
    this.currentProperty = property;
    $(document).on("keydown", this.keydown);
    $(document).on("mousedown", this.mousedown);
    this.$el.show();
    if (x + this.el.offsetWidth > window.innerWidth) {
      this.el.style.left = (x - this.el.offsetWidth) + "px";
    } else {
      this.el.style.left = x + "px";
    }
    if (y + this.el.offsetHeight > window.innerHeight) {
      return this.el.style.top = (y - this.el.offsetHeight) + "px";
    } else {
      return this.el.style.top = y + "px";
    }
  };

  ValueBinder.prototype.hide = function() {
    $(document).off("keydown", this.keydown);
    $(document).off("mousedown", this.mousedown);
    return this.$el.hide();
  };

  ValueBinder.prototype.mousedown = function(e) {
    if ($(e.target).closest(".value-binder-popup").length === 0) {
      return this.hide();
    }
  };

  ValueBinder.prototype.keydown = function(e) {
    if (e.keyCode === 27) {
      return this.hide();
    }
  };

  return ValueBinder;

})(Backbone.View);
