// Generated by CoffeeScript 1.12.7
var VJSButton,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSButton = (function(superClass) {
  extend(VJSButton, superClass);

  function VJSButton() {
    this.render = bind(this.render, this);
    this.up = bind(this.up, this);
    this.down = bind(this.down, this);
    return VJSButton.__super__.constructor.apply(this, arguments);
  }

  VJSButton.prototype.events = {
    'mousedown .vjs-button': 'down'
  };

  VJSButton.prototype.initialize = function() {
    VJSButton.__super__.initialize.call(this);
    this.button = document.createElement('div');
    this.button.className = 'vjs-button';
    this.el.appendChild(this.button);
    this.max = this.property.max;
    this.min = this.property.min;
    this.listenTo(this.model, "change:" + this.property.name, this.render);
    return this.render();
  };

  VJSButton.prototype.down = function(e) {
    if (e.button === 0) {
      if (this.property.toggle) {
        return this.model.set(this.property.name, !this.model.get(this.property.name));
      } else {
        this.model.set(this.property.name, true);
        return $(document).one("mouseup", this.up);
      }
    }
  };

  VJSButton.prototype.up = function() {
    return this.model.set(this.property.name, false);
  };

  VJSButton.prototype.render = function() {
    var value;
    value = this.model.get(this.property.name);
    if (value) {
      this.button.classList.add('active');
    } else {
      this.button.classList.remove('active');
    }
    return this.el;
  };

  return VJSButton;

})(VJSControl);
