// Generated by CoffeeScript 1.12.7
var VJSColorPicker,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSColorPicker = (function(superClass) {
  extend(VJSColorPicker, superClass);

  function VJSColorPicker() {
    this.render = bind(this.render, this);
    this.colorChange = bind(this.colorChange, this);
    return VJSColorPicker.__super__.constructor.apply(this, arguments);
  }

  VJSColorPicker.prototype.events = {
    "change .picker": "colorChange"
  };

  VJSColorPicker.prototype.initialize = function() {
    var div;
    VJSColorPicker.__super__.initialize.call(this);
    div = document.createElement('div');
    div.className = 'swatch';
    div.appendChild(this.picker = document.createElement('input'));
    this.picker.type = 'color';
    this.picker.className = 'picker';
    this.el.appendChild(div);
    return this.render();
  };

  VJSColorPicker.prototype.colorChange = function(e) {
    return this.model.set(this.property.name, e.target.value);
  };

  VJSColorPicker.prototype.render = function() {
    this.picker.value = this.model.get(this.property.name);
    return this.el;
  };

  return VJSColorPicker;

})(VJSControl);
