// Generated by CoffeeScript 1.12.7
var EffectsClasses, VJSEffectsLibraryView, VJSLibrary, VJSLibraryView,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

EffectsClasses = [ZoomBlurPass, InkPass, NoisePass, MirrorPass, InvertPass, ChromaticAberration, MirrorPass, DotRollPass, KaleidoscopePass, ShroomPass];

VJSLibrary = (function(superClass) {
  extend(VJSLibrary, superClass);

  function VJSLibrary() {
    return VJSLibrary.__super__.constructor.apply(this, arguments);
  }

  VJSLibrary.prototype.initialize = function() {
    VJSLibrary.instance = this;
    this.set("effects", EffectsClasses);
    return this.set("compositions", []);
  };

  VJSLibrary.prototype.addEffect = function(effect) {
    this.get("effects").push(effect);
    return this.trigger("change:effects");
  };

  VJSLibrary.prototype.addEffectFromFile = function(file) {
    var reader;
    reader = new FileReader;
    reader.file = file;
    reader.onload = (function(_this) {
      return function() {
        return _this.addEffect(ISFEffect.fromFile(file, reader.result));
      };
    })(this);
    return reader.readAsText(file);
  };

  return VJSLibrary;

})(Backbone.Model);

VJSLibraryView = (function(superClass) {
  extend(VJSLibraryView, superClass);

  function VJSLibraryView() {
    this.render = bind(this.render, this);
    return VJSLibraryView.__super__.constructor.apply(this, arguments);
  }

  VJSLibraryView.prototype.className = 'vjs-library';

  VJSLibraryView.prototype.initialize = function() {
    VJSLibraryView.__super__.initialize.call(this);
    this.effectsView = new VJSEffectsLibraryView({
      model: this.model
    });
    return this.el.appendChild(this.effectsView.render());
  };

  VJSLibraryView.prototype.render = function() {
    return this.el;
  };

  return VJSLibraryView;

})(Backbone.View);

VJSEffectsLibraryView = (function(superClass) {
  extend(VJSEffectsLibraryView, superClass);

  function VJSEffectsLibraryView() {
    this.render = bind(this.render, this);
    this.drop = bind(this.drop, this);
    this.dragleave = bind(this.dragleave, this);
    this.dragover = bind(this.dragover, this);
    this.dragenter = bind(this.dragenter, this);
    return VJSEffectsLibraryView.__super__.constructor.apply(this, arguments);
  }

  VJSEffectsLibraryView.prototype.events = {
    "dragenter": "dragenter",
    "dragover": "dragover",
    "dragleave": "dragleave",
    "drop": "drop"
  };

  VJSEffectsLibraryView.prototype.initialize = function() {
    var label;
    VJSEffectsLibraryView.__super__.initialize.call(this);
    this.el.appendChild(label = _V.div('label', "Effects Available"));
    this.el.appendChild(this.stack = _V.div('stack'));
    return this.listenTo(this.model, "change:effects", this.render);
  };

  VJSEffectsLibraryView.prototype.dragenter = function(e) {
    return e.preventDefault();
  };

  VJSEffectsLibraryView.prototype.dragover = function(e) {
    e.preventDefault();
    return this.el.classList.add('dragover');
  };

  VJSEffectsLibraryView.prototype.dragleave = function(e) {
    e.preventDefault();
    return this.el.classList.remove('dragover');
  };

  VJSEffectsLibraryView.prototype.drop = function(e) {
    var file;
    e.preventDefault();
    this.el.classList.remove('dragover');
    file = e.originalEvent.dataTransfer.files[0];
    return this.model.addEffectFromFile(file);
  };

  VJSEffectsLibraryView.prototype.render = function() {
    var effect, i, len, ref;
    this.stack.replaceChildren();
    ref = this.model.get("effects");
    for (i = 0, len = ref.length; i < len; i++) {
      effect = ref[i];
      this.stack.appendChild(_V.div('effect-list-item', effect.effectName));
    }
    return this.el;
  };

  return VJSEffectsLibraryView;

})(VJSCell);
