// Generated by CoffeeScript 1.12.7
var VJSLayerView,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSLayerView = (function(superClass) {
  extend(VJSLayerView, superClass);

  function VJSLayerView() {
    this.render = bind(this.render, this);
    this.compositionChanged = bind(this.compositionChanged, this);
    return VJSLayerView.__super__.constructor.apply(this, arguments);
  }

  VJSLayerView.prototype.initialize = function() {
    VJSLayerView.__super__.initialize.call(this);
    this.layerInspector = new LayerInspector({
      model: this.model
    });
    this.el.appendChild(this.layerInspector.el);
    this.el.appendChild(this.model.compositionPicker.render());
    this.inspector = new CompositionInspector({
      model: this.model
    });
    this.el.appendChild(this.inspector.el);
    this.el.appendChild(document.createElement('hr'));
    this.el.appendChild(this.model.effectsPanel.render());
    return this.listenTo(this.model, "change:composition", this.compositionChanged);
  };

  VJSLayerView.prototype.compositionChanged = function() {
    return this.inspector.setComposition(this.model.get("composition"));
  };

  VJSLayerView.prototype.render = function() {
    return this.el;
  };

  return VJSLayerView;

})(Backbone.View);
