// Generated by CoffeeScript 1.12.7
var VJSPopup,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSPopup = (function(superClass) {
  extend(VJSPopup, superClass);

  function VJSPopup() {
    this.keydown = bind(this.keydown, this);
    this.mousedown = bind(this.mousedown, this);
    this.hide = bind(this.hide, this);
    this.clickRow = bind(this.clickRow, this);
    return VJSPopup.__super__.constructor.apply(this, arguments);
  }

  VJSPopup.prototype.className = 'popup';

  VJSPopup.prototype.events = {
    'click .row': 'clickRow'
  };

  VJSPopup.prototype.initialize = function() {
    return document.body.appendChild(this.el);
  };

  VJSPopup.prototype.show = function(pos, options, callback) {
    var i, len, option, x, y;
    this.el.textContent = "";
    this.nextCallback = callback;
    for (i = 0, len = options.length; i < len; i++) {
      option = options[i];
      this.addOption(option);
    }
    $(document).on("keydown", this.keydown);
    $(document).on("mousedown", this.mousedown);
    this.el.style.display = 'block';
    if (pos.element) {
      x = pos.element.offsetLeft;
      y = $(pos.element).offset().top - $(window).scrollTop();
      this.el.style.width = pos.element.offsetWidth - 4 + "px";
    } else {
      x = pos.x;
      y = pos.y;
    }
    if (x + this.el.offsetWidth > window.innerWidth) {
      this.el.style.left = (x - this.el.offsetWidth) + "px";
    } else {
      this.el.style.left = x + "px";
    }
    if (y + this.el.offsetHeight > window.innerHeight) {
      return this.el.style.top = (y - this.el.offsetHeight) + "px";
    } else {
      return this.el.style.top = y + "px";
    }
  };

  VJSPopup.prototype.addOption = function(option) {
    var row;
    this.el.appendChild(row = document.createElement('div'));
    row.className = "row";
    return row.textContent = option;
  };

  VJSPopup.prototype.clickRow = function(e) {
    this.nextCallback(e.target.textContent);
    return this.hide();
  };

  VJSPopup.prototype.hide = function() {
    this.nextCallback = null;
    $(document).off("keydown", this.keydown);
    $(document).off("mousedown", this.mousedown);
    return this.$el.hide();
  };

  VJSPopup.prototype.mousedown = function(e) {
    if ($(e.target).closest(".popup").length === 0) {
      return this.hide();
    }
  };

  VJSPopup.prototype.keydown = function(e) {
    if (e.keyCode === 27) {
      return this.hide();
    }
  };

  return VJSPopup;

})(Backbone.View);
