// Generated by CoffeeScript 1.12.7
var VJSSelect,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSSelect = (function(superClass) {
  extend(VJSSelect, superClass);

  function VJSSelect() {
    this.render = bind(this.render, this);
    this.showPopup = bind(this.showPopup, this);
    this.change = bind(this.change, this);
    this.showBindings = bind(this.showBindings, this);
    return VJSSelect.__super__.constructor.apply(this, arguments);
  }

  VJSSelect.prototype.className = 'vjs-select';

  VJSSelect.prototype.events = {
    "click .row": "change",
    "click .button": "showPopup"
  };

  VJSSelect.prototype.showBindings = function() {
    return "do nothing";
  };

  VJSSelect.prototype.initialize = function() {
    VJSSelect.__super__.initialize.call(this);
    this.el.appendChild(this.button = this.div('button'));
    return this.el.appendChild(this.popup = this.div('popup'));
  };

  VJSSelect.prototype.change = function(e) {
    this.model.set(this.property.name, e.target.textContent.trim());
    return this.popup.style.display = "none";
  };

  VJSSelect.prototype.showPopup = function() {
    return this.popup.style.display = "block";
  };

  VJSSelect.prototype.render = function() {
    var i, len, opt, option, ref;
    this.button.textContent = this.model.get(this.property.name);
    this.popup.replaceChildren();
    ref = this.property.options;
    for (i = 0, len = ref.length; i < len; i++) {
      option = ref[i];
      this.popup.appendChild(opt = this.div('row', option));
    }
    return this.el;
  };

  return VJSSelect;

})(VJSControl);
