// Generated by CoffeeScript 1.12.7
var VJSSlider,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSSlider = (function(superClass) {
  extend(VJSSlider, superClass);

  function VJSSlider() {
    this.render = bind(this.render, this);
    this.click = bind(this.click, this);
    this.dragEnd = bind(this.dragEnd, this);
    this.dragMove = bind(this.dragMove, this);
    this.dragBegin = bind(this.dragBegin, this);
    return VJSSlider.__super__.constructor.apply(this, arguments);
  }

  VJSSlider.prototype.events = {
    "click .slider": "click",
    "mousedown .slider": "dragBegin"
  };

  VJSSlider.prototype.initialize = function() {
    var div;
    VJSSlider.__super__.initialize.call(this);
    div = document.createElement('div');
    div.className = 'slider';
    div.appendChild(this.level = document.createElement('div'));
    this.level.className = 'level';
    this.el.appendChild(div);
    this.max = this.property.max;
    this.min = this.property.min;
    this.listenTo(this.model, "change:" + this.property.name, this.render);
    return this.render();
  };

  VJSSlider.prototype.dragBegin = function(e) {
    if (e.button !== 0) {
      return;
    }
    $(document).on({
      'mousemove': this.dragMove,
      'mouseup': this.dragEnd
    });
    return this.click(e);
  };

  VJSSlider.prototype.dragMove = function(e) {
    return this.click(e);
  };

  VJSSlider.prototype.dragEnd = function(e) {
    return $(document).off({
      'mousemove': this.dragMove,
      'mouseup': this.dragEnd
    });
  };

  VJSSlider.prototype.click = function(e) {
    var percent, step, value, x;
    x = e.pageX - this.el.offsetLeft;
    percent = x / this.el.clientWidth;
    value = (this.max - this.min) * percent + this.min;
    value = Math.clamp(value, this.min, this.max);
    step = this.property.step;
    if (step) {
      return this.model.set(this.property.name, Math.round(value / step) * step);
    } else {
      return this.model.set(this.property.name, value);
    }
  };

  VJSSlider.prototype.render = function() {
    var percent, value;
    value = this.model.get(this.property.name);
    percent = (value - this.min) / (this.max - this.min) * 100;
    this.level.style.width = percent + "%";
    this.level.textContent = Math.roundTo(value, 2);
    return this.el;
  };

  return VJSSlider;

})(VJSControl);
