// Generated by CoffeeScript 1.12.7
var CanvasComposition, Composition, GLSLComposition,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Composition = (function(superClass) {
  extend(Composition, superClass);

  function Composition() {
    return Composition.__super__.constructor.apply(this, arguments);
  }

  Composition.prototype.generateThumbnail = function() {
    var renderer;
    renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: true,
      clearAlpha: 1,
      transparent: true
    });
    renderer.setSize(640, 480);
    this.setup(renderer);
    this.update();
    renderer.setClearColor(0xffffff, 0);
    renderer.render(this.scene, this.camera);
    this.thumbnail = document.createElement('img');
    this.thumbnail.src = renderer.domElement.toDataURL();
    return this.trigger("thumbnail-available");
  };

  Composition.prototype.setup = function(renderer) {};

  Composition.prototype.update = function() {};

  return Composition;

})(VJSBindable);

CanvasComposition = (function(superClass) {
  extend(CanvasComposition, superClass);

  function CanvasComposition() {
    return CanvasComposition.__super__.constructor.apply(this, arguments);
  }

  CanvasComposition.prototype.setup = function(renderer1) {
    this.renderer = renderer1;
    this.enabled = true;
    this.renderToScreen = false;
    this.needsSwap = true;
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene;
    this.canvas = document.createElement('canvas');
    this.canvas.width = this.renderer.domElement.width;
    this.canvas.height = this.renderer.domElement.height;
    this.texture = new THREE.Texture(this.canvas);
    this.texture.minFilter = THREE.LinearFilter;
    this.texture.magFilter = THREE.LinearFilter;
    this.material = new THREE.MeshBasicMaterial({
      map: this.texture
    });
    this.quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), this.material);
    this.scene.add(this.quad);
    return this.time = 0;
  };

  CanvasComposition.prototype.update = function() {
    this.time += 0.1;
    this.draw();
    if (this.texture) {
      return this.texture.needsUpdate = true;
    }
  };

  return CanvasComposition;

})(Composition);

GLSLComposition = (function(superClass) {
  extend(GLSLComposition, superClass);

  GLSLComposition.prototype.uniformValues = [];

  function GLSLComposition() {
    this._uniformsChanged = bind(this._uniformsChanged, this);
    this.createBinding = bind(this.createBinding, this);
    var i, len, ref, uniformDesc;
    GLSLComposition.__super__.constructor.call(this);
    this.uniforms = THREE.UniformsUtils.clone(this.findUniforms(this.fragmentShader));
    ref = this.uniformValues;
    for (i = 0, len = ref.length; i < len; i++) {
      uniformDesc = ref[i];
      this.inputs.push({
        name: uniformDesc.name,
        type: uniformDesc.type,
        min: uniformDesc.min,
        max: uniformDesc.max,
        "default": uniformDesc["default"]
      });
      this.listenTo(this, "change:" + uniformDesc.name, this._uniformsChanged);
      this.set(uniformDesc.name, uniformDesc["default"]);
    }
  }

  GLSLComposition.prototype.setup = function(renderer) {
    this.renderer = renderer;
    this.material = new THREE.ShaderMaterial({
      uniforms: this.uniforms,
      vertexShader: this.vertexShader,
      fragmentShader: this.fragmentShader
    });
    this.enabled = true;
    this.renderToScreen = false;
    this.needsSwap = true;
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene;
    this.quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), null);
    this.quad.material = this.material;
    return this.scene.add(this.quad);
  };

  GLSLComposition.prototype.bindToKey = function(property, target, targetProperty) {
    return this.listenTo(target, "change:" + targetProperty, this.createBinding(property));
  };

  GLSLComposition.prototype.createBinding = function(property) {
    return (function(_this) {
      return function(signal, value) {
        return _this.set(property.name, value);
      };
    })(this);
  };

  GLSLComposition.prototype._uniformsChanged = function(obj) {
    var name, ref, results, uniformDesc, value;
    ref = obj.changed;
    results = [];
    for (name in ref) {
      value = ref[name];
      uniformDesc = _.find(this.uniformValues, (function(u) {
        return u.name === name;
      }));
      results.push(this.uniforms[uniformDesc.uniform].value = value);
    }
    return results;
  };

  GLSLComposition.prototype.vertexShader = "varying vec2 vUv;\nvoid main() {\n  vUv = uv;\n  gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}";

  GLSLComposition.prototype.findUniforms = function(shader) {
    var i, len, line, lines, name, tokens, uniforms;
    lines = shader.split("\n");
    uniforms = {};
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      if (line.indexOf("uniform") === 0) {
        tokens = line.split(" ");
        name = tokens[2].substring(0, tokens[2].length - 1);
        uniforms[name] = this.typeToUniform(tokens[1]);
      }
    }
    return uniforms;
  };

  GLSLComposition.prototype.typeToUniform = function(type) {
    switch (type) {
      case "float":
        return {
          type: "f",
          value: 0
        };
      case "vec2":
        return {
          type: "v2",
          value: new THREE.Vector2
        };
      case "vec3":
        return {
          type: "v3",
          value: new THREE.Vector3
        };
      case "vec4":
        return {
          type: "v4",
          value: new THREE.Vector4
        };
      case "bool":
        return {
          type: "i",
          value: 0
        };
      case "sampler2D":
        return {
          type: "t",
          value: null
        };
    }
  };

  return GLSLComposition;

})(Composition);
