// Generated by CoffeeScript 1.12.7
var BlobbyComposition, SPEED,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SPEED = 1 / 20000;

BlobbyComposition = (function(superClass) {
  extend(BlobbyComposition, superClass);

  function BlobbyComposition() {
    return BlobbyComposition.__super__.constructor.apply(this, arguments);
  }

  BlobbyComposition.prototype.name = "Blobby";

  BlobbyComposition.prototype.inputs = [
    {
      name: "Level",
      type: "number",
      min: 0,
      max: 1,
      "default": 0
    }, {
      name: "Speed",
      type: "number",
      min: 0,
      max: 1,
      "default": .1
    }
  ];

  BlobbyComposition.prototype.setup = function(renderer) {
    var count, geometry, i, j, material, positions, seed, sprite;
    this.renderer = renderer;
    this.time = 0;
    this.scene = new THREE.Scene;
    this.camera = new THREE.PerspectiveCamera(75, this.renderer.domElement.width / this.renderer.domElement.height, 1, 10000);
    this.camera.position.z = 1000;
    sprite = window.createDiscTexture();
    count = 1001;
    positions = new Float32Array(count * 3);
    this.pointSeeds = new Float32Array(count);
    for (i = j = 0; j < count; i = ++j) {
      positions[i * 3] = 500 * Math.random() - 250;
      positions[i * 3 + 1] = 500 * Math.random() - 250;
      positions[i * 3 + 2] = 500 * Math.random() - 250;
      seed = i;
      this.pointSeeds[i] = seed;
    }
    geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    this.positions = positions;
    material = new THREE.PointsMaterial({
      size: 135,
      map: sprite,
      transparent: true,
      depthWrite: false
    });
    material.color.setHSL(1.0, 0.3, 0.7);
    material.opacity = 0.2;
    material.blending = THREE.AdditiveBlending;
    this.particles = new THREE.Points(geometry, material);
    return this.scene.add(this.particles);
  };

  BlobbyComposition.prototype.update = function() {
    var a, index, j, positionAttribute, ref, results, seed;
    this.time += .01 * this.get("Speed");
    this.particles.rotation.y += 0.01 * this.get("Speed");
    a = this.get("Level") * 500;
    a = a + 1;
    a = Math.max(a, 60);
    ref = this.pointSeeds;
    results = [];
    for (index = j = 0; j < ref.length; index = ++j) {
      seed = ref[index];
      this.positions[index * 3] = noise.simplex2(this.time, seed) * a;
      this.positions[index * 3 + 1] = noise.simplex2(seed, this.time) * a;
      results.push(this.positions[index * 3 + 2] = noise.simplex2(this.time + seed, seed) * a);
    }
    positionAttribute = this.particles.geometry.getAttribute('position');
    positionAttribute.needsUpdate = true;
    return results;
  };

  return BlobbyComposition;

})(Composition);
