// Generated by CoffeeScript 1.12.7
var CircleGrower,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CircleGrower = (function(superClass) {
  extend(CircleGrower, superClass);

  function CircleGrower() {
    this["change:Color"] = bind(this["change:Color"], this);
    return CircleGrower.__super__.constructor.apply(this, arguments);
  }

  CircleGrower.prototype.name = "Circles";

  CircleGrower.prototype.setup = function(renderer) {
    this.renderer = renderer;
    CircleGrower.__super__.setup.call(this, this.renderer);
    return this.color = new THREE.Color(this.get("Color"));
  };

  CircleGrower.prototype.inputs = [
    {
      name: "Color",
      type: "color",
      "default": "#ffffff"
    }, {
      name: "Speed",
      type: "number",
      min: -1,
      max: 1,
      "default": 0.4
    }
  ];

  CircleGrower.prototype.uniformValues = [
    {
      uniform: "circleSize",
      name: "Number Of Circles",
      type: "number",
      min: 0,
      max: 1,
      "default": .3
    }
  ];

  CircleGrower.prototype["change:Color"] = function(obj, val) {
    return this.color.setStyle(val);
  };

  CircleGrower.prototype.update = function() {
    this.uniforms.uSize.value.set(this.renderer.domElement.width, this.renderer.domElement.height);
    this.uniforms.time.value += this.get("Speed");
    return this.uniforms.color.value.set(this.color.r, this.color.g, this.color.b, 1);
  };

  CircleGrower.prototype.fragmentShader = "uniform vec2 uSize;\nvarying vec2 vUv;\nuniform float circleSize;\nuniform vec4 color;\nuniform float time;\nvoid main (void)\n{\n  float numCircles = circleSize * 10.0;\n  float cSize = 1.0 / numCircles;\n  vec2 pos = mod(vUv.xy * 2.0 - 1.0, vec2(cSize)) * numCircles - vec2(cSize * numCircles / 2.0);\n  float dist = sqrt(dot(pos, pos));\n  dist = dist * numCircles + time * -.050;\n\n  gl_FragColor = sin(dist * 2.0) > 0.0 ? color : vec4(0.0);\n\n}";

  return CircleGrower;

})(GLSLComposition);
