// Generated by CoffeeScript 1.12.7
var CubeReplication,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CubeReplication = (function(superClass) {
  extend(CubeReplication, superClass);

  function CubeReplication() {
    this["change:Color"] = bind(this["change:Color"], this);
    this["change:Trigger"] = bind(this["change:Trigger"], this);
    return CubeReplication.__super__.constructor.apply(this, arguments);
  }

  CubeReplication.prototype.name = "Cube Replication";

  CubeReplication.prototype.inputs = [
    {
      name: "Trigger",
      type: "boolean",
      toggle: false
    }, {
      name: "Color",
      type: "color",
      "default": "#ffffff"
    }
  ];

  CubeReplication.prototype.setup = function(renderer) {
    var arr, cubeSize, i, j, len, ref, ref1, results, results1, spacing, steps, x, y, z;
    this.renderer = renderer;
    this.scene = new THREE.Scene;
    this.camera = new THREE.PerspectiveCamera(75, this.renderer.domElement.width / this.renderer.domElement.height, 1, 10000);
    this.camera.position.z = 1000;
    this.origin = new THREE.Vector3(0, 0, 0);
    this.group = new THREE.Object3D;
    this.scene.add(this.group);
    this.matColor = new THREE.Color;
    this.material = new THREE.MeshBasicMaterial({
      transparent: true,
      color: this.matColor
    });
    this.material.blending = THREE.AdditiveBlending;
    this.material.opacity = 0.3;
    cubeSize = 40;
    this.cubeGeometry = new THREE.BoxGeometry(cubeSize, cubeSize, cubeSize);
    this.group = new THREE.Object3D;
    this.scene.add(this.group);
    steps = 10;
    spacing = 100;
    arr = (function() {
      results = [];
      for (var i = ref = -steps / 2, ref1 = steps / 2; ref <= ref1 ? i <= ref1 : i >= ref1; ref <= ref1 ? i++ : i--){ results.push(i); }
      return results;
    }).apply(this);
    this.cubes = [];
    results1 = [];
    for (j = 0, len = arr.length; j < len; j++) {
      x = arr[j];
      results1.push((function() {
        var k, len1, results2;
        results2 = [];
        for (k = 0, len1 = arr.length; k < len1; k++) {
          y = arr[k];
          results2.push((function() {
            var l, len2, results3;
            results3 = [];
            for (l = 0, len2 = arr.length; l < len2; l++) {
              z = arr[l];
              results3.push(this.addCube(this.group, new THREE.Vector3(x * spacing, y * spacing, z * spacing)));
            }
            return results3;
          }).call(this));
        }
        return results2;
      }).call(this));
    }
    return results1;
  };

  CubeReplication.prototype["change:Trigger"] = function(obj, val) {
    var cube, i, len, ref, results;
    if (val) {
      ref = this.cubes;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        cube = ref[i];
        if (Math.random() > 0.8) {
          results.push(cube.material.opacity = 1);
        } else {
          results.push(void 0);
        }
      }
      return results;
    }
  };

  CubeReplication.prototype["change:Color"] = function(obj, val) {
    var cube, i, len, ref, results;
    ref = this.cubes;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      cube = ref[i];
      results.push(cube.material.color.setStyle(val));
    }
    return results;
  };

  CubeReplication.prototype.addCube = function(group, pos) {
    var cube, material;
    material = new THREE.MeshBasicMaterial({
      transparent: true
    });
    material.blending = THREE.AdditiveBlending;
    material.opacity = 0.3;
    cube = new THREE.Mesh(this.cubeGeometry, material);
    this.cubes.push(cube);
    group.add(cube);
    return cube.position.set(pos.x, pos.y, pos.z);
  };

  CubeReplication.prototype.update = function() {
    var cube, i, len, ref;
    ref = this.cubes;
    for (i = 0, len = ref.length; i < len; i++) {
      cube = ref[i];
      if (cube.material.opacity > .3) {
        cube.material.opacity -= .03;
      }
    }
    this.group.rotation.x += .001;
    this.group.rotation.y += .00133;
    return this.group.rotation.z += .00143;
  };

  return CubeReplication;

})(Composition);
