// Generated by CoffeeScript 1.12.7
var ImageComposition,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ImageComposition = (function(superClass) {
  extend(ImageComposition, superClass);

  function ImageComposition(imageFile) {
    this.imageFile = imageFile;
    this.update = bind(this.update, this);
    ImageComposition.__super__.constructor.call(this);
    this.name = this.imageFile.name;
    this.animate = this.imageFile.type === "image/gif";
  }

  ImageComposition.prototype.setup = function(renderer) {
    this.renderer = renderer;
    this.enabled = true;
    this.renderToScreen = false;
    this.needsSwap = true;
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene;
    this.image = document.createElement("img");
    this.image.src = URL.createObjectURL(this.imageFile);
    return this.image.addEventListener("load", (function(_this) {
      return function(e) {
        _this.gifCanvas = document.createElement("canvas");
        _this.gifCanvas.width = _this.image.width;
        _this.gifCanvas.height = _this.image.height;
        _this.imageTexture = new THREE.Texture(_this.gifCanvas);
        _this.imageTexture.minFilter = THREE.LinearFilter;
        _this.imageTexture.magFilter = THREE.LinearFilter;
        _this.imageTexture.needsUpdate = true;
        _this.material = new THREE.MeshBasicMaterial({
          map: _this.imageTexture,
          side: THREE.DoubleSide
        });
        _this.quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), _this.material);
        return _this.scene.add(_this.quad);
      };
    })(this));
  };

  ImageComposition.prototype.update = function() {
    var ctx;
    if (this.animate && this.imageTexture) {
      ctx = this.gifCanvas.getContext("2d");
      ctx.drawImage(this.image, 0, 0);
      return this.imageTexture.needsUpdate = true;
    }
  };

  return ImageComposition;

})(Composition);
