// Generated by CoffeeScript 1.12.7
var RandomShapeComposition,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

RandomShapeComposition = (function(superClass) {
  extend(RandomShapeComposition, superClass);

  RandomShapeComposition.prototype.name = "Random Shapes";

  function RandomShapeComposition() {
    this["change:Square"] = bind(this["change:Square"], this);
    this["change:Circle"] = bind(this["change:Circle"], this);
    this["change:Triangle"] = bind(this["change:Triangle"], this);
    this["change:trigger"] = bind(this["change:trigger"], this);
    RandomShapeComposition.__super__.constructor.call(this);
    this.shapes = [];
  }

  RandomShapeComposition.prototype.inputs = [
    {
      name: "trigger",
      type: "boolean"
    }, {
      name: "Triangle",
      type: "boolean"
    }, {
      name: "Square",
      type: "boolean"
    }, {
      name: "Circle",
      type: "boolean"
    }, {
      name: "Fill",
      type: "boolean",
      toggle: true
    }, {
      name: "color",
      type: "color",
      "default": "#FF0000"
    }
  ];

  RandomShapeComposition.prototype["change:trigger"] = function(obj, val) {
    var shape;
    if (val) {
      shape = ["Square", "Triangle", "Circle"][Math.floor(Math.random() * 3)];
      return this.shapes.push({
        shape: shape,
        life: 1
      });
    }
  };

  RandomShapeComposition.prototype["change:Triangle"] = function(obj, val) {
    if (val) {
      return this.shapes.push({
        shape: "Triangle",
        life: 1
      });
    }
  };

  RandomShapeComposition.prototype["change:Circle"] = function(obj, val) {
    if (val) {
      return this.shapes.push({
        shape: "Circle",
        life: 1
      });
    }
  };

  RandomShapeComposition.prototype["change:Square"] = function(obj, val) {
    if (val) {
      return this.shapes.push({
        shape: "Square",
        life: 1
      });
    }
  };

  RandomShapeComposition.prototype.draw = function() {
    var ctx, i, len, ref, shape, size;
    ctx = this.canvas.getContext("2d");
    ctx.save();
    ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    ctx.strokeStyle = ctx.fillStyle = this.get("color").toString();
    ctx.lineWidth = 5;
    ctx.translate(this.canvas.width / 2, this.canvas.height / 2);
    ref = this.shapes;
    for (i = 0, len = ref.length; i < len; i++) {
      shape = ref[i];
      ctx.globalAlpha = shape.life;
      size = 150 + 300 * (1 - shape.life);
      this["draw" + shape.shape](ctx, size);
      shape.life -= 0.03;
    }
    this.shapes = this.shapes.filter(function(s) {
      return s.life > 0;
    });
    ctx.globalAlpha = 1;
    return ctx.restore();
  };

  RandomShapeComposition.prototype.drawSquare = function(ctx, size) {
    if (this.get("Fill")) {
      return ctx.fillRect(-size / 2, -size / 2, size, size);
    } else {
      return ctx.strokeRect(-size / 2, -size / 2, size, size);
    }
  };

  RandomShapeComposition.prototype.drawCircle = function(ctx, size) {
    ctx.beginPath();
    ctx.arc(0, 0, size / 2, size / 2, 0, 2 * Math.PI, false);
    if (this.get("Fill")) {
      return ctx.fill();
    } else {
      return ctx.stroke();
    }
  };

  RandomShapeComposition.prototype.drawTriangle = function(ctx, size) {
    var p1x, p1y, p2x, p2y;
    ctx.beginPath();
    ctx.moveTo(0, -size / 2);
    p1x = size / 2 * Math.sin(2 * Math.PI / 3);
    p1y = -size / 2 * Math.cos(2 * Math.PI / 3);
    ctx.lineTo(p1x, p1y);
    p2x = size / 2 * Math.sin(4 * Math.PI / 3);
    p2y = -size / 2 * Math.cos(4 * Math.PI / 3);
    ctx.lineTo(p2x, p2y);
    ctx.closePath();
    if (this.get("Fill")) {
      return ctx.fill();
    } else {
      return ctx.stroke();
    }
  };

  return RandomShapeComposition;

})(CanvasComposition);
