// Generated by CoffeeScript 1.12.7
var ShapeSlideComposition,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ShapeSlideComposition = (function(superClass) {
  extend(ShapeSlideComposition, superClass);

  ShapeSlideComposition.prototype.name = "Shape Slide";

  function ShapeSlideComposition() {
    this["change:Square"] = bind(this["change:Square"], this);
    this["change:Circle"] = bind(this["change:Circle"], this);
    this["change:Triangle"] = bind(this["change:Triangle"], this);
    this["change:trigger"] = bind(this["change:trigger"], this);
    ShapeSlideComposition.__super__.constructor.call(this);
    this.shapes = [];
  }

  ShapeSlideComposition.prototype.inputs = [
    {
      name: "trigger",
      type: "boolean"
    }, {
      name: "Triangle",
      type: "boolean"
    }, {
      name: "Square",
      type: "boolean"
    }, {
      name: "Circle",
      type: "boolean"
    }, {
      name: "Fill",
      type: "boolean",
      toggle: true,
      "default": true
    }, {
      name: "color",
      type: "color",
      "default": "#FF0000"
    }
  ];

  ShapeSlideComposition.prototype["change:trigger"] = function(obj, val) {
    var shape;
    if (val) {
      shape = ["Square", "Triangle", "Circle"][Math.floor(Math.random() * 3)];
      return this.shapes.push({
        shape: shape,
        life: 1
      });
    }
  };

  ShapeSlideComposition.prototype["change:Triangle"] = function(obj, val) {
    if (val) {
      return this.shapes.push({
        shape: "Triangle",
        life: 0
      });
    }
  };

  ShapeSlideComposition.prototype["change:Circle"] = function(obj, val) {
    if (val) {
      return this.shapes.push({
        shape: "Circle",
        life: 0
      });
    }
  };

  ShapeSlideComposition.prototype["change:Square"] = function(obj, val) {
    if (val) {
      return this.shapes.push({
        shape: "Square",
        life: 0
      });
    }
  };

  ShapeSlideComposition.prototype.draw = function() {
    var ctx, i, len, ref, shape, size;
    ctx = this.canvas.getContext("2d");
    ctx.save();
    ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    ctx.strokeStyle = ctx.fillStyle = this.get("color").toString();
    ctx.lineWidth = 5;
    ctx.translate(this.canvas.width / 2, this.canvas.height / 2);
    ref = this.shapes;
    for (i = 0, len = ref.length; i < len; i++) {
      shape = ref[i];
      ctx.globalAlpha = 1;
      size = 150 + 300 * (1 - shape.life);
      this["draw" + shape.shape](ctx, shape);
      shape.life += 0.02;
    }
    this.shapes = this.shapes.filter(function(s) {
      return s.life < 2;
    });
    ctx.restore();
    return ctx.globalAlpha = 1;
  };

  ShapeSlideComposition.prototype.drawSquare = function(ctx, shape) {
    var life;
    life = shape.life;
    if (life < 1) {
      life = easeInOutQuad(life, 0, 1, 1);
      if (this.get("Fill")) {
        return ctx.fillRect(-250, -250, 500, 500 * life);
      } else {
        return ctx.strokeRect(-250, -250, 500, 500 * life);
      }
    }
  };

  ShapeSlideComposition.prototype.drawCircle = function(ctx, shape) {
    var life, size, theta;
    life = shape.life;
    if (life < 1) {
      life = easeOutQuad(life, 0, 1, 1);
    }
    if (life === 0) {
      return;
    }
    size = 250;
    if (life > 1) {
      size -= 50 * (life - 1);
    }
    if (life > 1) {
      ctx.globalAlpha = Math.clamp(1 - (life - 1) * 2, 0, 1);
    }
    ctx.beginPath();
    if (this.get("Fill")) {
      ctx.moveTo(0, 0);
      ctx.lineTo(500 / 2, 0);
    }
    theta = -Math.min(life, 1) * 2 * Math.PI;
    ctx.arc(0, 0, size, 0, theta, true);
    if (this.get("Fill")) {
      return ctx.fill();
    } else {
      return ctx.stroke();
    }
  };

  ShapeSlideComposition.prototype.drawTriangle = function(ctx, size) {
    var p1x, p1y, p2x, p2y;
    ctx.beginPath();
    ctx.moveTo(0, -size / 2);
    p1x = size / 2 * Math.sin(2 * Math.PI / 3);
    p1y = -size / 2 * Math.cos(2 * Math.PI / 3);
    ctx.lineTo(p1x, p1y);
    p2x = size / 2 * Math.sin(4 * Math.PI / 3);
    p2y = -size / 2 * Math.cos(4 * Math.PI / 3);
    ctx.lineTo(p2x, p2y);
    ctx.closePath();
    if (this.get("Fill")) {
      return ctx.fill();
    } else {
      return ctx.stroke();
    }
  };

  return ShapeSlideComposition;

})(CanvasComposition);
