// Generated by CoffeeScript 1.12.7
var SphereSphereComposition,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SphereSphereComposition = (function(superClass) {
  extend(SphereSphereComposition, superClass);

  function SphereSphereComposition() {
    this.update = bind(this.update, this);
    return SphereSphereComposition.__super__.constructor.apply(this, arguments);
  }

  SphereSphereComposition.prototype.name = "Spherize";

  SphereSphereComposition.prototype.setup = function(renderer) {
    var i, len, ref, res, results, size, skeleton, sprite;
    this.renderer = renderer;
    this.scene = new THREE.Scene;
    this.scene.fog = new THREE.FogExp2(0x000000, 0.0005);
    this.camera = new THREE.PerspectiveCamera(75, this.renderer.domElement.width / this.renderer.domElement.height, 1, 10000);
    this.camera.position.z = 1000;
    this.origin = new THREE.Vector3(0, 0, 0);
    this.group = new THREE.Object3D;
    this.scene.add(this.group);
    sprite = window.createDiscTexture();
    this.material = new THREE.PointsMaterial({
      size: 35,
      map: sprite,
      transparent: true,
      depthWrite: false
    });
    this.material.blending = THREE.AdditiveBlending;
    this.material.opacity = 0.2;
    this.material.color.setHSL(1.0, 0.3, 0.7);
    ref = [400];
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      size = ref[i];
      res = 80;
      skeleton = new THREE.SphereGeometry(size, res, res);
      this.particles = new THREE.Points(skeleton, this.material);
      results.push(this.group.add(this.particles));
    }
    return results;
  };

  SphereSphereComposition.prototype.update = function() {
    this.group.rotation.y += 0.001;
    this.group.rotation.z += 0.0001;
    return this.group.rotation.x += 0.00014;
  };

  SphereSphereComposition.prototype.addCube = function(group, position) {
    var mesh;
    mesh = new THREE.Mesh(this.sphereGeometry, this.sphereMaterial);
    mesh.position = position;
    mesh.lookAt(this.origin);
    return this.group.add(mesh);
  };

  return SphereSphereComposition;

})(Composition);
