// Generated by CoffeeScript 1.12.7
var VideoComposition,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VideoComposition = (function(superClass) {
  extend(VideoComposition, superClass);

  VideoComposition.prototype.name = "Video";

  VideoComposition.prototype.inputs = [
    {
      name: "Playing",
      type: "boolean",
      toggle: true,
      "default": true
    }
  ];

  function VideoComposition(videoFile) {
    var videoTag;
    this.videoFile = videoFile;
    this["change:Playing"] = bind(this["change:Playing"], this);
    VideoComposition.__super__.constructor.call(this);
    if (this.videoFile) {
      this.name = this.videoFile.name;
      videoTag = document.createElement('video');
      videoTag.src = URL.createObjectURL(this.videoFile);
      videoTag.addEventListener('loadeddata', (function(_this) {
        return function(e) {
          var canvas, context, f;
          videoTag.currentTime = videoTag.duration / 2;
          canvas = document.createElement('canvas');
          canvas.width = videoTag.videoWidth;
          canvas.height = videoTag.videoHeight;
          context = canvas.getContext('2d');
          f = function() {
            if (videoTag.readyState !== videoTag.HAVE_ENOUGH_DATA) {
              setTimeout(f, 100);
              return;
            }
            context.drawImage(videoTag, 0, 0);
            _this.thumbnail = document.createElement('img');
            _this.thumbnail.src = canvas.toDataURL();
            videoTag.pause();
            videoTag = null;
            return _this.trigger("thumbnail-available");
          };
          return setTimeout(f, 100);
        };
      })(this));
    }
  }

  VideoComposition.prototype.setup = function(renderer) {
    this.renderer = renderer;
    this.enabled = true;
    this.renderToScreen = false;
    this.needsSwap = true;
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene;
    this.video = document.createElement('video');
    this.video.src = URL.createObjectURL(this.videoFile);
    this.video.load();
    this.video.play();
    this.video.volume = 0;
    this.video.loop = true;
    return this.video.addEventListener('loadeddata', (function(_this) {
      return function() {
        _this.videoTexture = new THREE.VideoTexture(_this.video);
        _this.videoTexture.minFilter = THREE.LinearFilter;
        _this.videoTexture.magFilter = THREE.LinearFilter;
        _this.videoTexture.generateMipmaps = false;
        _this.material = new THREE.MeshBasicMaterial({
          map: _this.videoTexture
        });
        _this.quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), _this.material);
        return _this.scene.add(_this.quad);
      };
    })(this));
  };

  VideoComposition.prototype["change:Playing"] = function(model, playing) {
    if (playing) {
      return this.video.play();
    } else {
      return this.video.pause();
    }
  };

  VideoComposition.prototype.update = function() {
    if (this.videoTexture) {
      return this.videoTexture.needsUpdate = true;
    }
  };

  return VideoComposition;

})(Composition);
