// Generated by CoffeeScript 1.12.7
var VJSBindable,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSBindable = (function(superClass) {
  extend(VJSBindable, superClass);

  function VJSBindable() {
    this.createBinding = bind(this.createBinding, this);
    this.clearBinding = bind(this.clearBinding, this);
    var i, input, j, len, len1, output, ref, ref1, ref2, ref3;
    this.inputs = ((ref = this.inputs) != null ? ref.slice() : void 0) || [];
    this.outputs = ((ref1 = this.outputs) != null ? ref1.slice() : void 0) || [];
    this.bindings = {};
    VJSBindable.__super__.constructor.call(this);
    ref2 = this.outputs;
    for (i = 0, len = ref2.length; i < len; i++) {
      output = ref2[i];
      this.set(output.name, output["default"] || 0);
    }
    ref3 = this.inputs;
    for (j = 0, len1 = ref3.length; j < len1; j++) {
      input = ref3[j];
      this.setDefault(input);
      if (this["change:" + input.name]) {
        this.listenTo(this, "change:" + input.name, this["change:" + input.name]);
      }
      if (input.autoconnect) {
        this.autoconnect(input);
      }
    }
  }

  VJSBindable.prototype.autoconnect = function(input) {
    var key, obj, objname, ref;
    ref = input.autoconnect.split("."), objname = ref[0], key = ref[1];
    obj = application.globalSignals[objname];
    return this.bindToKey(input, obj, key);
  };

  VJSBindable.prototype.setDefault = function(input) {
    if (input["default"] !== void 0) {
      return this.set(input.name, input["default"]);
    } else if (input.type === "number") {
      return this.set(input.name, 0);
    } else if (input.type === "boolean") {
      return this.set(input.name, false);
    } else if (input.type === "color") {
      return this.set(input.name, 0xFFFFFF);
    }
  };

  VJSBindable.prototype.clearBinding = function(property) {
    var binding;
    if (this.bindings[property]) {
      binding = this.bindings[property];
      return binding.target.off("change:" + binding.targetProperty, binding.callback);
    }
  };

  VJSBindable.prototype.bindToKey = function(property, target, targetProperty) {
    var f;
    this.clearBinding(property.name);
    f = this.createBinding(property);
    this.bindings[property.name] = {
      callback: f,
      target: target,
      targetProperty: targetProperty
    };
    return target.on("change:" + targetProperty, f);
  };

  VJSBindable.prototype.createBinding = function(property) {
    return (function(_this) {
      return function(signal, value) {
        var v;
        if ((typeof value) === property.type) {
          return _this.set(property.name, value);
        } else {
          v = _this.convertTypes(value, property.type);
          return _this.set(property.name, v);
        }
      };
    })(this);
  };

  VJSBindable.prototype.convertTypes = function(value, type) {
    if (type === "boolean") {
      return !!value;
    }
    if (type === "number") {
      if (typeof value === "boolean") {
        if (value) {
          return 1;
        } else {
          return 0;
        }
      }
    }
    return value;
  };

  VJSBindable.prototype.getCustomViews = function() {};

  VJSBindable.prototype.serialize = function() {
    var data, key, ref, value;
    data = {
      className: this.className || this.constructor.name,
      name: this.name,
      cid: this.cid,
      bindings: {}
    };
    ref = this.bindings;
    for (key in ref) {
      value = ref[key];
      data.bindings[key] = {
        target: value.target.cid,
        targetProperty: value.targetProperty
      };
    }
    return data;
  };

  VJSBindable.inflate = function(data) {
    var Clazz, obj;
    Clazz = VJSBindable.classRegistry[data.className] || window[data.className];
    if (!Clazz) {
      throw new Error("Unknown bindable class: " + data.className);
    }
    obj = new Clazz;
    obj.oldCid = data.cid;
    data.inflated = obj;
    return obj;
  };

  VJSBindable.registerClass = function(name, Clazz) {
    if (name && Clazz) {
      return VJSBindable.classRegistry[name] = Clazz;
    }
  };

  VJSBindable.classRegistry = {};

  return VJSBindable;

})(Backbone.Model);
