// Generated by CoffeeScript 1.12.7
var AUTO_LAUNCH_COMP, App, RUN,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

RUN = true;

AUTO_LAUNCH_COMP = CubeReplication;

noise.seed(Math.random());

$(function() {
  window.CompositionClasses = [CubeReplication, BlobbyComposition, CircleGrower, FlameComposition, ISFComposition, RandomShapeComposition, ShapeSlideComposition, SphereSphereComposition];
  return window.application = new App;
});

App = (function(superClass) {
  extend(App, superClass);

  function App() {
    this.save = bind(this.save, this);
    this.loadInitialState = bind(this.loadInitialState, this);
    this.rebind = bind(this.rebind, this);
    this.load = bind(this.load, this);
    this.registerSerializableClasses = bind(this.registerSerializableClasses, this);
    this.setOutputCanvas = bind(this.setOutputCanvas, this);
    this.popout = bind(this.popout, this);
    this.animate = bind(this.animate, this);
    window.application = this;
    this.globalSignals = {};
    this.library = new VJSLibrary();
    this.initStats();
    this.initSignals();
    this.initLayers();
    this.registerSerializableClasses();
    this.load();
    requestAnimationFrame(this.animate);
    $(".pop-out").click(this.popout);
    if (!RUN) {
      $(document).keydown((function(_this) {
        return function(e) {
          if (e.keyCode === 82) {
            return _this.animate();
          }
        };
      })(this));
    }
  }

  App.prototype.animate = function() {
    var time;
    time = Date.now();
    this.signalManager.update(time);
    this.mixer.render();
    if (this.externalOutputCanvas && this.externalOutputContext) {
      if (this.externalOutputCanvas.width !== this.mixer.canvas.width || this.externalOutputCanvas.height !== this.mixer.canvas.height) {
        this.externalOutputCanvas.width = this.mixer.canvas.width;
        this.externalOutputCanvas.height = this.mixer.canvas.height;
      }
      this.externalOutputContext.drawImage(this.mixer.canvas, 0, 0, this.externalOutputCanvas.width, this.externalOutputCanvas.height);
    }
    this.stats.update();
    if (RUN) {
      return requestAnimationFrame(this.animate);
    }
  };

  App.prototype.popout = function() {
    if (!this.outputWindow || this.outputWindow.closed) {
      this.outputWindow = window.open("output.html", "vjs-output", "popup=1,width=1024,height=768");
    }
    if (this.outputWindow) {
      return this.outputWindow.focus();
    }
  };

  App.prototype.setOutputCanvas = function(canvas) {
    this.externalOutputCanvas = canvas;
    if (this.externalOutputCanvas) {
      return this.externalOutputContext = this.externalOutputCanvas.getContext("2d");
    }
  };

  App.prototype.initLayers = function() {
    var canvas, frame, outputWindow, tabs;
    this.libraryView = new VJSLibraryView({
      model: this.library
    });
    canvas = document.querySelector('#output');
    frame = document.querySelector(".output-frame");
    this.layer1 = new VJSLayer({
      name: "Layer 1",
      canvas: canvas,
      frame: frame
    });
    if (AUTO_LAUNCH_COMP) {
      this.layer1.setComposition(new AUTO_LAUNCH_COMP);
    }
    this.layer1View = new VJSLayerView({
      model: this.layer1
    });
    this.layer2 = new VJSLayer({
      name: "Layer 2",
      canvas: canvas,
      frame: frame
    });
    this.layer2View = new VJSLayerView({
      model: this.layer2
    });
    outputWindow = document.querySelector(".output-frame");
    this.mixer = new VJSLayerMixer({
      output: outputWindow,
      canvas: canvas,
      frame: frame,
      layers: [this.layer1, this.layer2]
    });
    tabs = [
      {
        name: "Layer 1",
        view: this.layer1View.render()
      }, {
        name: "Layer 2",
        view: this.layer2View.render()
      }, {
        name: "Library",
        view: this.libraryView.render()
      }, {
        name: "Output",
        view: document.createElement('div')
      }
    ];
    return tabs = new TabSet(document.querySelector('.layers-section'), tabs);
  };

  App.prototype.initStats = function() {
    this.stats = new Stats;
    return document.body.appendChild(this.stats.domElement);
  };

  App.prototype.initSignals = function() {
    var filters, set, tabset;
    this.signalManager = new SignalManager;
    this.signalManagerView = new SignalManagerView({
      model: this.signalManager
    });
    filters = document.createElement('div');
    filters.textContent = "Filter content";
    set = [
      {
        name: "Signals",
        view: this.signalManagerView.render()
      }
    ];
    tabset = new TabSet(document.querySelector('.signal-section'), set);
    return this.valueBinder = new ValueBinder({
      model: this.signalManager
    });
  };

  App.prototype.registerSerializableClasses = function() {
    var i, klass, len, ref, results;
    ref = [FallingSignal, LFO, Clock, Palette, ColorGenerator, Sequencer, MIDI, Gamepad, AudioInput, Keyboard, InvertSignal, ZoomBlurPass, InkPass, NoisePass, MirrorPass, InvertPass, ChromaticAberration, DotRollPass, KaleidoscopePass, ShroomPass, FeedbackPass];
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      klass = ref[i];
      if (klass) {
        results.push(VJSBindable.registerClass(klass.name, klass));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  App.prototype.load = function() {
    var effects, needsRebinding, signals;
    this.state = JSON.parse(localStorage.getItem("state"));
    if (!this.state) {
      return this.loadInitialState();
    }
    needsRebinding = [];
    signals = this.signalManager.unserialize(this.state.signals);
    needsRebinding = needsRebinding.concat(signals);
    effects = this.layer1.unserialize(this.state.layer1);
    needsRebinding = needsRebinding.concat(effects);
    effects = this.layer2.unserialize(this.state.layer2);
    needsRebinding = needsRebinding.concat(effects);
    return this.rebind(needsRebinding);
  };

  App.prototype.rebind = function(bindables) {
    var binding, i, key, len, property, results, signalInfo, target;
    results = [];
    for (i = 0, len = bindables.length; i < len; i++) {
      signalInfo = bindables[i];
      results.push((function() {
        var ref, results1;
        ref = signalInfo.bindings;
        results1 = [];
        for (key in ref) {
          binding = ref[key];
          target = _.find(this.signalManager.models, function(m) {
            return m.oldCid === binding.target;
          });
          property = _.find(signalInfo.inflated.inputs, function(input) {
            return input.name === key;
          });
          results1.push(signalInfo.inflated.bindToKey(property, target, binding.targetProperty));
        }
        return results1;
      }).call(this));
    }
    return results;
  };

  App.prototype.loadInitialState = function() {
    this.signalManager.add(this.midi = new MIDI);
    this.signalManager.add(this.clock = new Clock);
    this.signalManager.add(this.gamepad = new Gamepad);
    this.signalManager.add(this.audio = new AudioInput);
    this.signalManager.add(this.keyboard = new Keyboard);
    this.globalSignals.Clock = this.clock;
    this.globalSignals.Keyboard = this.keyboard;
    return this.globalSignals.Audio = this.audio;
  };

  App.prototype.save = function() {
    var data;
    data = {
      signals: this.signalManager.serialize(),
      layer1: this.layer1.serialize(),
      layer2: this.layer2.serialize()
    };
    localStorage.setItem("state", JSON.stringify(data));
    return data;
  };

  return App;

})(Backbone.Model);
