// Generated by CoffeeScript 1.12.7
$(function() {
  $(document.body).on("dragover", function(e) {
    return e.preventDefault();
  });
  return $(document.body).on("drop", function(e) {
    return e.preventDefault();
  });
});
