// Generated by CoffeeScript 1.12.7
var RGBShiftPass, RGBShiftShader;

RGBShiftPass = (function() {
  function RGBShiftPass(r, g, b) {
    var shader;
    shader = new RGBShiftShader;
    this.uniforms = THREE.UniformsUtils.clone(shader.uniforms);
    this.uniforms['uRedShift'].value = r;
    this.uniforms['uGreenShift'].value = g;
    this.uniforms['uBlueShift'].value = b;
    this.material = new THREE.ShaderMaterial({
      uniforms: this.uniforms,
      vertexShader: shader.vertexShader,
      fragmentShader: shader.fragmentShader
    });
    this.enabled = true;
    this.renderToScreen = false;
    this.needsSwap = true;
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene();
    this.quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), null);
    this.scene.add(this.quad);
  }

  RGBShiftPass.prototype.render = function(renderer, writeBuffer, readBuffer, delta) {
    this.uniforms['uTex'].value = (readBuffer != null ? readBuffer.texture : void 0) || readBuffer;
    this.uniforms['uSize'].value.set(readBuffer.width, readBuffer.height);
    this.quad.material = this.material;
    if (this.renderToScreen) {
      renderer.setRenderTarget(null);
      return renderer.render(this.scene, this.camera);
    } else {
      renderer.setRenderTarget(writeBuffer);
      renderer.clear();
      renderer.render(this.scene, this.camera);
      return renderer.setRenderTarget(null);
    }
  };

  return RGBShiftPass;

})();

RGBShiftShader = (function() {
  function RGBShiftShader() {}

  RGBShiftShader.prototype.uniforms = {
    uTex: {
      type: 't',
      value: null
    },
    uSize: {
      type: 'v2',
      value: new THREE.Vector2(256, 256)
    },
    uRedShift: {
      type: 'f',
      value: 0.0
    },
    uGreenShift: {
      type: 'f',
      value: 0.0
    },
    uBlueShift: {
      type: 'f',
      value: 1.0
    }
  };

  RGBShiftShader.prototype.vertexShader = "varying vec2 vUv;\nvoid main() {\n  vUv = uv;\n  gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}";

  RGBShiftShader.prototype.fragmentShader = "uniform sampler2D uTex;\nuniform float uRedShift;\nuniform float uGreenShift;\nuniform float uBlueShift;\nuniform vec2 uSize;\n\nvarying vec2 vUv;\n\nvoid main() {\n  float r = texture2D(uTex, (vUv - 0.5) * vec2(uRedShift, 1.0) + 0.5).r;\n  float g = texture2D(uTex, (vUv - 0.5) * vec2(uGreenShift, 1.0) + 0.5).g;\n  float b = texture2D(uTex, (vUv - 0.5) * vec2(uBlueShift, 1.0) + 0.5).b;\n  \n  gl_FragColor = vec4(r,g,b,1.0);\n}";

  return RGBShiftShader;

})();
