// Generated by CoffeeScript 1.12.7
Math.clamp = function(val, min, max) {
  return Math.min(max, Math.max(val, min));
};

Math.roundTo = function(val, places) {
  var power;
  power = Math.pow(10, places);
  return Math.round(val * power) / power;
};

Math.fract = function(val) {
  return val - Math.floor(val);
};

window.createDiscTexture = function(size) {
  var canvas, context, gradient, radius, texture;
  if (size == null) {
    size = 256;
  }
  canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  context = canvas.getContext('2d');
  radius = size / 2;
  gradient = context.createRadialGradient(radius, radius, 0, radius, radius, radius);
  gradient.addColorStop(0, 'rgba(255, 255, 255, 1)');
  gradient.addColorStop(0.75, 'rgba(255, 255, 255, 0.7)');
  gradient.addColorStop(1, 'rgba(255, 255, 255, 0)');
  context.fillStyle = gradient;
  context.beginPath();
  context.arc(radius, radius, radius, 0, Math.PI * 2);
  context.fill();
  texture = new THREE.CanvasTexture(canvas);
  texture.minFilter = THREE.LinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.generateMipmaps = false;
  return texture;
};
