// Generated by CoffeeScript 1.12.7
var VJSLayer,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSLayer = (function(superClass) {
  extend(VJSLayer, superClass);

  VJSLayer.prototype.readonly = true;

  VJSLayer.prototype.inputs = [
    {
      name: "opacity",
      type: "number",
      min: 0,
      max: 1,
      "default": 1
    }, {
      name: "Blend Mode",
      type: "select",
      options: ['Normal', 'Additive', 'Subtractive', 'Multiply', 'AdditiveAlpha'],
      "default": 'Normal'
    }
  ];

  function VJSLayer(properties) {
    this.unserialize = bind(this.unserialize, this);
    this.serialize = bind(this.serialize, this);
    this.eject = bind(this.eject, this);
    this.texture = bind(this.texture, this);
    this.output = bind(this.output, this);
    this.render = bind(this.render, this);
    var outputWindow;
    VJSLayer.__super__.constructor.call(this);
    this.name = properties.name || ("Layer " + this.cid);
    this.renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: true,
      clearAlpha: 0,
      transparent: true
    });
    outputWindow = properties.frame;
    this.renderer.setSize(outputWindow.offsetWidth, outputWindow.offsetHeight);
    $(window).resize((function(_this) {
      return function() {
        _this.renderer.setSize(outputWindow.offsetWidth, outputWindow.offsetHeight);
        if (_this.composer != null) {
          return _this.composer.setSize(outputWindow.offsetWidth, outputWindow.offsetHeight);
        }
      };
    })(this));
    this.initCompositions();
    this.initEffects();
  }

  VJSLayer.prototype.render = function() {
    var ref;
    if (this.get("composition")) {
      if ((ref = this.get("composition")) != null) {
        ref.update();
      }
      return this.composer.render();
    }
  };

  VJSLayer.prototype.output = function() {
    return this.renderer.domElement;
  };

  VJSLayer.prototype.texture = function() {
    var ref;
    return ((ref = this.composer.readBuffer) != null ? ref.texture : void 0) || this.renderTarget.texture;
  };

  VJSLayer.prototype.initCompositions = function() {
    var clazz, i, len, results;
    this.compositionPicker = new CompositionPicker(this);
    results = [];
    for (i = 0, len = CompositionClasses.length; i < len; i++) {
      clazz = CompositionClasses[i];
      results.push(this.compositionPicker.addComposition(new clazz));
    }
    return results;
  };

  VJSLayer.prototype.initEffects = function() {
    var parameters, passthrough;
    parameters = {
      minFilter: THREE.LinearFilter,
      magFilter: THREE.LinearFilter,
      format: THREE.RGBAFormat,
      stencilBuffer: false
    };
    this.renderTarget = new THREE.WebGLRenderTarget(this.renderer.domElement.width, this.renderer.domElement.height, parameters);
    this.composer = new THREE.EffectComposer(this.renderer, this.renderTarget);
    this.composer.setSize(this.renderer.domElement.width, this.renderer.domElement.height);
    this.renderModel = new THREE.RenderPass(new THREE.Scene, new THREE.PerspectiveCamera);
    this.renderModel.emptyScene = this.renderModel.scene;
    this.renderModel.emptyCamera = this.renderModel.camera;
    this.renderModel.enabled = true;
    this.composer.addPass(this.renderModel);
    passthrough = new Passthrough;
    passthrough.enabled = true;
    passthrough.renderToScreen = false;
    passthrough.needsSwap = true;
    this.composer.addPass(passthrough);
    this.effectsManager = new EffectsManager(this.composer);
    return this.effectsPanel = new EffectsPanel({
      model: this.effectsManager
    });
  };

  VJSLayer.prototype.eject = function() {
    return this.setComposition(null);
  };

  VJSLayer.prototype.setComposition = function(comp) {
    this.unload(this.get("composition"));
    this.set("composition", comp);
    if (comp) {
      comp.set("active", true);
      this.listenTo(comp, "destroy", this.eject);
      comp.setup(this.renderer);
      this.renderModel.scene = comp.scene;
      return this.renderModel.camera = comp.camera;
    } else {
      this.renderModel.scene = this.renderModel.emptyScene;
      this.renderModel.camera = this.renderModel.emptyCamera;
      this.renderer.setRenderTarget(this.renderTarget);
      this.renderer.clear(true, true, true);
      return this.renderer.setRenderTarget(null);
    }
  };

  VJSLayer.prototype.unload = function(comp) {
    if (comp) {
      comp.set("active", false);
      return this.stopListening(comp);
    }
  };

  VJSLayer.prototype.load = function(effects) {
    var effect, i, len, results;
    results = [];
    for (i = 0, len = effects.length; i < len; i++) {
      effect = effects[i];
      results.push(this.effectsManager.add(effect));
    }
    return results;
  };

  VJSLayer.prototype.serialize = function() {
    var properties;
    properties = VJSLayer.__super__.serialize.apply(this, arguments);
    properties.effects = this.effectsManager.serialize();
    return properties;
  };

  VJSLayer.prototype.unserialize = function(state) {
    var effect, effectInfo, i, len, ref;
    ref = state.effects;
    for (i = 0, len = ref.length; i < len; i++) {
      effectInfo = ref[i];
      effect = VJSBindable.inflate(effectInfo);
      this.effectsManager.addEffectToStack(effect);
    }
    return state.effects;
  };

  return VJSLayer;

})(VJSBindable);
