// Generated by CoffeeScript 1.12.7
var VJSLayerMixer, VJSMixerRenderPass,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

VJSLayerMixer = (function(superClass) {
  extend(VJSLayerMixer, superClass);

  function VJSLayerMixer() {
    this.render = bind(this.render, this);
    this.initRenderer = bind(this.initRenderer, this);
    return VJSLayerMixer.__super__.constructor.apply(this, arguments);
  }

  VJSLayerMixer.prototype.initialize = function() {
    VJSLayerMixer.__super__.initialize.call(this);
    this.output = this.get("output");
    this.canvas = this.get("canvas");
    this.canvas.width = this.output.offsetWidth;
    this.canvas.height = this.output.offsetHeight;
    $(window).resize((function(_this) {
      return function() {
        _this.canvas.width = _this.output.offsetWidth;
        return _this.canvas.height = _this.output.offsetHeight;
      };
    })(this));
    return this.initRenderer();
  };

  VJSLayerMixer.prototype.initRenderer = function() {
    var outputWindow;
    this.renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: true,
      clearAlpha: 0,
      transparent: true,
      canvas: this.canvas
    });
    outputWindow = document.querySelector(".output-frame");
    this.renderer.setSize(outputWindow.offsetWidth, outputWindow.offsetHeight);
    $(window).resize((function(_this) {
      return function() {
        return _this.renderer.setSize(outputWindow.offsetWidth, outputWindow.offsetHeight);
      };
    })(this));
    this.composer = new THREE.EffectComposer(this.renderer);
    this.compositePass = new VJSMixerRenderPass(this.get("layers"));
    this.compositePass.setup(this.renderer);
    return this.composer.addPass(this.compositePass);
  };

  VJSLayerMixer.prototype.render = function() {
    var i, layer, len, ref, results;
    ref = this.get("layers");
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      layer = ref[i];
      results.push(layer.render());
    }
    return results;
  };

  return VJSLayerMixer;

})(Backbone.Model);

VJSMixerRenderPass = (function() {
  function VJSMixerRenderPass(layers) {
    this.layers = layers;
    this.render = bind(this.render, this);
    this.layerSets = [];
  }

  VJSMixerRenderPass.prototype.setup = function(renderer1) {
    var i, layer, len, material, quad, ref, results;
    this.renderer = renderer1;
    this.enabled = true;
    this.renderToScreen = true;
    this.needsSwap = true;
    this.camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    this.scene = new THREE.Scene;
    ref = this.layers;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      layer = ref[i];
      material = new THREE.MeshBasicMaterial({
        map: layer.texture()
      });
      material.depthTest = false;
      material.transparent = true;
      quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), material);
      this.scene.add(quad);
      results.push(this.layerSets.push({
        layer: layer,
        material: material
      }));
    }
    return results;
  };

  VJSMixerRenderPass.prototype.render = function(renderer, writeBuffer, readBuffer, delta) {
    var i, layer, layerSet, len, mat, ref;
    ref = this.layerSets;
    for (i = 0, len = ref.length; i < len; i++) {
      layerSet = ref[i];
      mat = layerSet.material;
      layer = layerSet.layer;
      mat.map = layer.texture();
      mat.blending = THREE[(layer.get('Blend Mode')) + "Blending"];
      mat.opacity = layer.get("opacity");
    }
    return renderer.render(this.scene, this.camera);
  };

  VJSMixerRenderPass.prototype.setSize = function() {};

  return VJSMixerRenderPass;

})();
